### ISSUE TITLE
Can't send Boolean Meshes from Blender to Zbrush wit GoB

### ISSUE THREAD

**Issue by OliverMilas** [JoseConseco/GoB#12]
Hi, everytime I applied a boolean operation on a mesh in Blender (with collapsed Modifier) and try to export with GoB,  Zbrush crashes on Import ... has anybody the same issue?

Manually importing the mesh (obj) works 

Thanks

**Comment by kromar** [comment]
@OliverMilas cah you share a blend file with a mesh that crashes? that would make it a lot easier to reproduce the issue.
i tried it with a decimation modifier (collapse) and a boolean after it but did not experience a crash.
i did some changes to the modifiers in the version i use so maybe its an issue only happening on earlier versions. (there is a open pull request for the changes)

![image](https://user-images.githubusercontent.com/1472884/54352554-37445b00-4652-11e9-9711-10951b56576f.png)

**Comment by OliverMilas** [comment]
hello kromar, thanks for the fast reply - sure here it is - i use blender 2.8 


[boolean_test.zip](https://github.com/JoseConseco/GoB/files/2966176/boolean_test.zip)

**Comment by kromar** [comment]
as far as i can tell this is related to the n-gons that get exported from blender which zbrush cant handle. 
I have made some fixes for the modifiers in the 2.7 script, and @JoseConseco mentioned that he wants to see how to deal with modifiers in the 2.8 version. 
We will need to see how we can bring the changes from 2.7 into 2.8 and go from there.

As a temporary solution you can put a triangulation modifier on the object, that should avoid the crashing.

**Comment by kromar** [comment]
It seems that in the 2.7 version n-gons get triangulated but not with the 2.8 version, and that is then causing zbrush to crash.

**Comment by OliverMilas** [comment]
@kromar Thank you will try that ^^

**Comment by kromar** [comment]
@OliverMilas this should be fixed in the latest 2.8 branch, would be great if you could give it a try.

**Comment by JoseConseco** [comment]
It if fixed. Closing
