### ISSUE TITLE
If there is a period in Blender object name, it will be converted to underscore.

### ISSUE THREAD

**Issue by Tsukasa-YAMATO** [JoseConseco/GoB#122]
![2020-06-25_03h09_09](https://user-images.githubusercontent.com/65609416/85610399-eebb8000-b691-11ea-835d-29dc168d6d1d.jpg)

There is no name mismatch, but I don't understand why the period in Blender is changed to an underscore. Is it necessary?

I tried it a little and Zbrush could import it as a sub tool name even if there is a period in the ZTL file name, so if Blender converts the period to an underscore, it may be easy to fix.

Please let me know if there is a need for that conversion. If you have an underscore on the Blender side, it is a little inconvenient, such as Foo_001.001, Foo_001.002, or Foo_001_001.001 by auto incrementing feature.

Environment
Windows 10 Pro, Zbrush 2020.1.4, GoB 3.3.10, Blender 2.83.

**Comment by kromar** [comment]
i do not know why this is done, maybe because the dot is often used for file extensions and goz has issues importing it, but thats speculation at this point. i will have a look if it is needed.

**Comment by JoseConseco** [comment]
zbrush cant read . and converts them _ automatically as far as I remember. That is why GOB converts . to _ , so then when asset comes back from zbrush, then name will match.

**Comment by kromar** [comment]
I can confirm that zbrush cant read the .001 and will remove it so you end up with objects that have the same name. What was strange however was that the name in my tests have also been changed in blender which should not happen and as far as i remember never did.

**Comment by Tsukasa-YAMATO** [comment]
@JoseConseco 
Thank you for your reply.
Certainly, when I changed the '_' in line 1117 of GoB.py to '.' and tested it, the GoZ cache file name had a period, but it was read into Zbrush until just before the period. As you say, this is very troublesome.

And to avoid this, it is reasonable to use an underscore and to chage both of them from period to underscore. I agree with you.

Thank you for your explanation.

@kromar 
Now I understand the need for this conversion. However, it is likely to be unknown information for many users. It's better adding some explanation about this replacement feature to the manual.

**Comment by kromar** [comment]
@Tsukasa-YAMATO i added a note to the manual update task to add some infomration on the limitation of object name extensions.

Do the object names in blender change for you to a underline as well? that would be good to know so we might be able to think about a solution for this

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
Of course in my Blender the period is changed to underscore after GoB export. That is a device of Mr. Jose. I also agree. This makes the object name in Blender and the sub tool name in Zbrush common due to the underscore. It is a mechanism that avoids name mismatch.

Please see the attached image carefully.

![2020-06-25_03h09_09](https://user-images.githubusercontent.com/65609416/85610399-eebb8000-b691-11ea-835d-29dc168d6d1d.jpg)

I think you can understand. I think a solution is not needed. I understand this is a mandatory implementation. :)
Unless Zbrush can properly import GoZ files with periods (there is this limitation of GoZ feature), we wouldn't have a workaround.

That's why I think Mr.Jose may have closed this thread.
