### ISSUE TITLE
Vertex Colors entry "Col" is not created in Blender when Zbrush transfers an object that has never been polypainted

### ISSUE THREAD

**Issue by Tsukasa-YAMATO** [JoseConseco/GoB#123]
This is a trivial bug. Not fatal.

![2020-06-26_23h56_04](https://user-images.githubusercontent.com/65609416/85873085-9dcf9700-b80b-11ea-98d1-08ed7887c315.jpg)

![2020-06-26_23h54_34](https://user-images.githubusercontent.com/65609416/85873346-f3a43f00-b80b-11ea-9c0f-8624b1200ed6.jpg)

Reproduction procedure
--------------
1. Open a template project, for example Demo Anime Head
2. GoB transfer
3. Click the shading tab and enter material preview mode
4. Since there is no vertex color entry called Col, it is displayed in black due to a broken link (bug)

However, if the user is painting with Polypaint on Zbrush, the Col entry is created correctly and this issue will not occur.

In the first place, users who don't use Polypaint will probably not even notice this bug, because they often do modeling in solid mode.

So in the end it's a trivial bug for the user and not fatal. (But I found it. :) )

It's probably easy to fix, so it's enough that you apply the fix to the next stable version.

By the way, the version number should be a value that is not Ver.3.3.10. For example, Ver.3.3.11. If you don't so, it's difficult for me to announce to my friends for the correct latest version.

Environment
------
GoB 3.3.10, Blender 2.83, Windows10, Zbrush 2020.1.4,

**Comment by kromar** [comment]
thanks for the report. yes this should be easy to fix, what would be the desired behavior from your side. that it does not create the node when no vertex color is created or create a empty node?
I would go for not creating the node if you agree on that.

**Comment by Tsukasa-YAMATO** [comment]
I've just found a new bug. And that is unavoidable if you implement your suggestion.

![2020-06-27_01h13_32](https://user-images.githubusercontent.com/65609416/85878488-bc399080-b813-11ea-86fe-d5afb43e542f.jpg)


I tried transferring the Dog with an extremely light gray of RGB:253,253,253. But no Col entry was created. There is a bug in threshold judgment.

So a quick implementation should always create a Col entry if it's set to do as in preferences.

But if you can solve this threshold problem, I think it's not ideal behavior to create a material if it's RGB:255,255,255.

The best
------
Solve this threshold problem, and don't create material  if all of the polypaint colors are RGB:255,255,255.


Better
------------
Create a Col group even if RGB:255,255,255 as long as "material :from polypaint" is selected.


Maybe the solution to this threshold problem is all. :)

**Comment by kromar** [comment]
that is a interesting find, remembers me on a comment i made in the code about a 250 max value. i guess i will have a look at that one:D

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
Please observe the source code carefully.
In general, 24-bit true color is 8 bits for each of red, green, and blue, that is, 256 colors (0 to 255). very important.
So pure white is RGB:255,255,255 in general.

For thresholds, you can get the answer by testing RGB:254,254,254, which is more stringent than above RGB:253,253,253, and in the other had pure white is RGB:255,255,255.

(I'm very skeptical about the number 250. )

**Comment by kromar** [comment]
i made fixes for both, no clue why there was such a limitation built in so i removed it. So far it seems to work for the full range for me.

increased version to V3.3.12 (note this does not include the scaling options which are in v3.3.11)
https://github.com/kromar/blender_GoB/tree/bugfix/vertex-color-limitation

**Comment by Tsukasa-YAMATO** [comment]
@kromar
Thank you for quick fix. I've tested it.
Unfortunately the handling between thresholds 254 and 255 is incorrect.
Nodes are not created with RGB:254,254,254.

![2020-06-27_03h18_49](https://user-images.githubusercontent.com/65609416/85889022-a5039e80-b825-11ea-9638-e494d654ec5f.jpg)

Please check again.

**Comment by kromar** [comment]
Hm strange, it did work for me even at 255, let me have another look.

**Comment by Tsukasa-YAMATO** [comment]
It is correct that if RGB: 255, 255, 255 no node is created, however, for RGB: 254, 254, 254 a node should be created.
It's a threshold issue.

**Comment by kromar** [comment]
i pushed a fix, the material was created before the vertex color so on the first push since there was no vertex color the node would not be created. The materials are now generated after the textures and vertex data is imported.
Lets see if this is solving your issue.

**Comment by Tsukasa-YAMATO** [comment]
It's pretty sleepy but got download it and tested it.

https://github.com/JoseConseco/GoB/issues/123#issuecomment-650266291

I think you finally adopted "better plan, not the best pan" in the comments above, is that correct?
Because the node was created even in the case of pure white RGB:255,255,255.
In other words, does it always  creating nodes when that is the case in the preference settings as so?
For me, either is fine, but please tell me which one you implemented. I want to give the correct information to my friends.

What I want to know is how to solve the threshold problem. I want to know if ”the best solution or the better solution”  below.

https://github.com/JoseConseco/GoB/issues/123#issuecomment-650266291

Tell me the way you adopted.

Really see you after 12 hours or later. Zzzz

**Comment by kromar** [comment]
> I think you finally adopted "better plan, not the best pan" in the comments above, is that correct?
not sure what you want to ask with that

For a node to be created from polypaint/vertex color the Material import needs to be set to Polypaint. 
![image](https://user-images.githubusercontent.com/1472884/85918660-026b1000-b865-11ea-93fa-959e9747a9d0.png)

Now with the Material import set to Polypaint there are these  conditions for the node creation: 
1. if no vertex color is created/imported no node setup will be created
![image](https://user-images.githubusercontent.com/1472884/85899622-a077bf80-b7fe-11ea-93e7-f28709e92281.png)

2. if a vertex color is imported, the material node is created
![image](https://user-images.githubusercontent.com/1472884/85900153-9904e600-b7ff-11ea-9fe0-54bf3ff50ffc.png)

**Comment by Tsukasa-YAMATO** [comment]
I am sorry that I wrote a difficult sentence.

(The reason I was confused at the time was that when I transferred a Dog with a poly paint color of RGB:254,254,254 to Blender, the Col entry was created but the material node wasn't. It was strange.
However, when I downloaded it again now and tested it, it worked fine. And with RGB:255,255,255, white Col entry and material nodes were created as well. No problem.  The bug was fixed.)

-------
@kromar 
By the way, I have tested it.
I just tried and found that if "From :Polypaint" is selected in the import settings, Col entry and nodes are created in any case.
(Even if it is RGB:255,255,255 or RGB:254,254,254)

The bug was fixed.
Now when I GoB export a new project with Zbrush, it avoids the black object in material preview.

Thank you for your quick fix.

**Comment by kromar** [comment]
im glad to hear that it works for you as well now! one more bug down:D

**Comment by Tsukasa-YAMATO** [comment]
By the way, it's a trivial matter, but I think Blender 2.83 is the mainstream, so I think you should also change the following description to 2.83. Although it doesn't affect the functionality of GoB at all. :)

Line 38 of init.py.

![2020-06-27_21h48_07](https://user-images.githubusercontent.com/65609416/85922962-07aa7800-b8c2-11ea-8118-13f0657df446.jpg)

**Comment by kromar** [comment]
This shows the minimum API version and is set to 2.82 because facemaps have been added there and not available in earlier versions. 
There is no limitation for 2.83 only at the moment, and therefore the min version 2.82 still applies here.

**Comment by Tsukasa-YAMATO** [comment]
I understand. I didn't know it was a minimum requirement. Though I don't know anything about Blender's Python in the first place.  :D
I think it's a very embarrassing question, so you can delete the question and your comment and this with your own authority. :)
