### ISSUE TITLE
removing version from addon name and work with tags/branches

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#13]
I had a quick go to see what is needed to bring the changes from 2.7 into the 2.8 version and its a issue that the filename was changed since that makes porting changes a manual job.
My suggestion would be that we remove the version from the file name and work with branches/tags to keep the versions apart.
Since it will take up to a year until 2.8 is production ready i expect a few more fixes/improvements coming our way and it would be good if we can maintain both versions in a easy way.

**Comment by JoseConseco** [comment]
Ok, I will change that. Btw. do you know how to put single file script like gob.py , into blender addons/ directory, without git trying to add all files from all addons sub directories to repo? For multifile addons it is easy, because you have separate folder that can be cloned to addons/ folder.

**Comment by kromar** [comment]
you can just put it in a folder and name the python script __init__.py that should do it but might look a bit strange.

**Comment by JoseConseco** [comment]
It is done.
