### ISSUE TITLE
Bl export to zb is normal, zb import bl does not respond

### ISSUE THREAD

**Issue by 1608372122** [JoseConseco/GoB#144]
Bl export to zb is normal, zb import bl does not respond

**Comment by kromar** [comment]
Please provide some more information, this is not enough to do anything.
What version are you using?
Are there any errors in the console ?
What are your configurations?
You have the import enabled?
Some screenshots or example files?

**Comment by 1608372122** [comment]
Thanks Reply







I don't know if the operation is correct，No response when clicking import

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JoseConseco/GoB"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月23日(星期四) 下午2:42
收件人:&nbsp;"JoseConseco/GoB"<GoB@noreply.github.com&gt;;
抄送:&nbsp;"1608372122"<1608372122@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JoseConseco/GoB] Bl export to zb is normal, zb import bl does not respond (#144)





 
Please provide some more information, this is not enough to do anything.
 What version are you using?
 Are there any errors in the console ?
 What are your configurations?
 You have the import enabled?
 Some screenshots or example files?

**Comment by kromar** [comment]
can you tell me the following, 

1. did you copy the Blender folder which is inside the addon to the Public>GoZApps folder?
![image](https://user-images.githubusercontent.com/1472884/88314283-f748ba00-cd14-11ea-9c7d-56e691e7d327.png)

2. what version of blender are you using?
![image](https://user-images.githubusercontent.com/1472884/88314352-121b2e80-cd15-11ea-9e74-113bd52c7b0f.png)

3. what version of the addon do you have installed?
![image](https://user-images.githubusercontent.com/1472884/88314434-34ad4780-cd15-11ea-829f-1a28764ba27f.png)

4. is the import button active (orange)
![image](https://user-images.githubusercontent.com/1472884/88314504-4e4e8f00-cd15-11ea-8cc3-5fea2c23e5be.png)

5. did you try to restart zbrush and blender after configuring GoZ in zbrush?
6. you could try fixing GoZ by running the goz installer which can be found where zbrush is installed?
![image](https://user-images.githubusercontent.com/1472884/88314690-92da2a80-cd15-11ea-8383-a15c0e3a5222.png)
