### ISSUE TITLE
addon not loading if "." (dot) in folder name

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#15]
if we have a "." in the branch name /addon folder name after extraction the addon is not loading with blender 2.8.

![image](https://user-images.githubusercontent.com/1472884/55001647-5e494800-4fd5-11e9-9d95-9f0f08ebe7c6.png)

**Comment by JoseConseco** [comment]
so I have to rename branch to eg: blender_28 ?
Then it should work.

**Comment by kromar** [comment]
yeah i think that should work. i wonder if its something we should report to the blender foundation, i have the feeling that blender thinks its a file with some extension and therefore does not recognize it as a folder.

**Comment by JoseConseco** [comment]
And it is done. new branch name is: GoZ-Blender_28
For now I think blender devs have hands full of work with 2000bug reported .
