### ISSUE TITLE
test on MacOS

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#157]
organize a mac to test the setup and execution changes

**Comment by GiuseppeBufalo** [comment]
I got this error when I try to export to zbrush

<img width="623" alt="Screenshot 2020-08-28 at 11 31 37" src="https://user-images.githubusercontent.com/28225091/91511066-1f35c980-e922-11ea-95fa-a72bd0682b9e.png">

**Comment by GiuseppeBufalo** [comment]
the problem it's with the latest version 3.4.5. it works with the 3.0.6

**Comment by kromar** [comment]
@GiuseppeBufalo  can you try the latest master? i changed it in one of the latest omits and it would be great to see if that works on a mac since i do not have a system to test on that OS.
https://codeload.github.com/kromar/blender_GoB/zip/GoZ-Blender_28
 https://github.com/kromar/blender_GoB/archive/GoZ-Blender_28.zip

**Comment by GiuseppeBufalo** [comment]
I tried to install it but i couldn't activate the addon 
<img width="755" alt="Screenshot 2020-08-29 at 11 27 52" src="https://user-images.githubusercontent.com/28225091/91625462-f4fc0e80-e9ea-11ea-9b00-f7b6bced525f.png">

**Comment by GiuseppeBufalo** [comment]
I'm using the 3.3.8 and it works well.

**Comment by kromar** [comment]
thanks for testing, yes there has been a big rewrite and changes on the installation of the addon so i currently expect some errors on MacOS since i have not been able to test it.
