### ISSUE TITLE
Permission denied error on export

### ISSUE THREAD

**Issue by kelheor** [JoseConseco/GoB#159]
When I'm trying to export model from Blender to ZBrush, I'm getting this error:

Traceback (most recent call last):
  File "C:\Users\kelheor\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\GoB\GoB.py", line 1301, in execute
    Popen([PATH_ZBRUSH, PATH_SCRIPT])
  File "C:\Program Files\Blender Foundation\blender-2.8\2.83\python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\blender-2.8\2.83\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Отказано в доступе

location: <unknown location>:-1

I tried to run Blender as an administrator - it didn't help.

Project path: C:\Users\Public\Pixologic\GoZProjects\Default\
ZBrush path: C:\Program Files\Pixologic\ZBrush 2021\

Any ideas on how to fix that?

**Comment by kromar** [comment]
@kelheor thanks for reporting the issue, can you tell me what version you are using?

**Comment by kromar** [comment]
also you can try to uninstall python if you have it installed and install the latest version, apparently there have been some permission issues with earlier versions that could cause this: https://www.python.org/downloads/

**Comment by kelheor** [comment]
GoB_Import.zsc works fine. Moreover, import from ZBrush to Blender also works fine. But export from Blender to Zbrush gives such error.

Blender version: 2.83.5
Python version: 3.7.8 
I'm using Python from Anaconda and can't change it, since other apps from conda repo relaying on this version.

Actually, old versions of GoB worked fine, but when ZBrush 2021 was released, I downloaded the latest version of GoB from Github and got such error.

**Comment by kromar** [comment]
have you tried with the standard python?
there have been changes in the last version of the addon to bypass zbrushes import to fix some issues and the execution there fore changed. that is where you for some reason get your errors when the .ZSC should be run with zbrsuh.

**Comment by kelheor** [comment]
I tried to install Python 3.8.5 right now - same issue. I think the problem is that Blender using its own python with 3.7.4 version (I checked path from logs: C:\Program Files\Blender Foundation\blender-2.8\2.83\python).

**Comment by kromar** [comment]
@kelheor thanks for testing with the latest python version. at this point im a bit out of ideas what could be the problem, the Popen command is creating a subprocess to start the script with zbrush and that is done via a windows command. So somewhere in that chain must be a permission problem. 
You have given blender admin permission as far as i understood and that did not help so i think its safe to assume that its not on that side. I also dont see that it could be on the zbrush side but with the windows command that is used to run start the script with zbrush.

Im not sure how this can be solved. Can you tell me if you are on that system as Normal or as Administrator user account?

**Comment by kelheor** [comment]
I'm using an Administrator account. No antivirus.
Today I tried to use GoB addon on my other PC, where it was worked with ZBrush 2021 after I updated GoB and suddenly I got the same error, which is really frustrated since I thought it might be PC-related issue. Currently have no ideas too about how to fix that.

**Comment by kelheor** [comment]
Well, today it seems I found how to fix that issue (not sure 100% and might be a coincidence). 
One of my other plugins in Blender also stopped working for no reason and I decided just to disable it in addons list and enable it again. And it started to work again. Then I recalled about GoB and disabled and enabled it again - and error is gone.

**Comment by kromar** [comment]
im happy to hear that you have been able to fix the issue and for letting me know that a possible solution.

**Comment by kelheor** [comment]
Some additional info: after I updated to 2.90 release, I got this error again. And when I re-enabled the addon without restarting Blender, I was asked to select Zbrush.exe file, but in Zbrush directory, I wasn't able to find any .exe files from Blender's file selector dialog - only directories - even if they were at place. After restart Blender, I finally was able to select Zbrush.exe. It seems that there is an issue with losing access to .exe file for some reason.

**Comment by kromar** [comment]
sounds like the 2.83 config was not transfered to 2.9 so that would explain why it asks you again for the zbrush location. 
The error however is a bit strange and i would like to be able to reproduce it.

Did you first send a object from blender to zbrush after enabling the addon? Or did you try to directly send a object from zbrush to blender after enabling it?
When enabling it you should send one object from blender to zbrush which will setup the files required for zbrush to work so maybe thats what causes the error.

i noticed that there is some problem with the filter in the blender file browser, it should just show you the zbrush.exe but for some reason not always works.
i did a fix for this that will filter for executable instead but maybe theres similar issue with that.
https://github.com/kromar/blender_GoB/tree/bugfix/filter-for-zbrush-executable

**Comment by kelheor** [comment]
Well, I always rename the config directory manually in AppData\Roaming\Blender Foundation\Blender after migrating to a new version, so all settings should be transferred to the new version. 

Actually, your addon asked for ZBrush location automatically, when I disabled it and then re-enabled after permission error (in the moment when I checked the checkbox). What is also strange, that if I disable it without permission error and then re-enable it, it won't automatically ask for ZBrush location and also lose its location for some reason (but not other settings, like Project Path).

Did you first send an object from blender to ZBrush after enabling the addon? - No, I didn't even close the preferences window when I got the file selection dialog.

**Comment by kromar** [comment]
when you open a new blender version for the first time there should be a option on the splash screen that asks you if you want to transfer your previous settings so you would not need to do that manually.
![image](https://user-images.githubusercontent.com/1472884/91895420-82fc2180-ec97-11ea-98b5-ba9f444fc002.png)


yeah that is a bit strange i will see what could happen there. 
It should only ask for zbrush when the path is not set in the preferences and you export without it specified.

**Comment by kromar** [comment]
aha i can reproduce the issue when i specify the folder and not the executable as zbrush path. 

![image](https://user-images.githubusercontent.com/1472884/91895862-32d18f00-ec98-11ea-8b38-af59c3323f74.png)

![image](https://user-images.githubusercontent.com/1472884/91896038-85ab4680-ec98-11ea-85d5-c2d602684bea.png)

i assume this is what happend to you so i will see if i can somehow find a solution to avoid such a mistake.

**Comment by kelheor** [comment]
I see. So the problem is that for some reason addon removed "ZBrush.exe" part from the path.
Maybe you can automatically add ZBrush.exe to the path if it's missing at the end of the path? I have big doubts that somebody will rename this exe and if there wasn't such a file at the location, at least the user will get an error about a missing file and not about permission error.

**Comment by kromar** [comment]
yes that is exactly what i want to try. i also want to avoid that a user is able to put in just the path in the first place, that is also possible when the exe is not selected and will result in the error. 
Maybe its related to what we encountered that sometimes the filter shows the executable and sometime it doesnt, and that is removing the executable from the path as well for some reason. 

Hehe yeah highly unlikely that the file is renamed:D
