### ISSUE TITLE
 Import failure to blender

### ISSUE THREAD

**Issue by Msuzuki003** [JoseConseco/GoB#161]
When I try to import the model that was reduced with the decimation master with zbrush with GoB of Blender, it always shuts down. I'm having trouble importing.

ZBrush2021.1.1
Blender2.83
GoB 3.4.8

**Comment by kromar** [comment]
can you share that decimated model or one that causes the crash? that would really help to find out whats happeing.

**Comment by Msuzuki003** [comment]
[SampleScene.zip](https://github.com/JoseConseco/GoB/files/5159427/SampleScene.zip)
Thank you for your reply. Upload the scene data that can be loaded with Load Tool from ZBrush Tool.

**Comment by kromar** [comment]
thanks for sharing the file, it also crashes for me so i might figure out whats going wrong

**Comment by kromar** [comment]
![image](https://user-images.githubusercontent.com/1472884/92028645-ac36b380-ed64-11ea-92ad-ba4b957e12c4.png)

![image](https://user-images.githubusercontent.com/1472884/92028590-945f2f80-ed64-11ea-9e2e-3c5778e98a3b.png)
that mesh has detached edges youc an check it in the mesh integrity and you can also fix it there and you should be able to transfer it. i will see if ican fix this on the import side

**Comment by Msuzuki003** [comment]
Thank you. The problem is resolved. 
I didn't know about the check function on ZBrush side, so thank you for letting me know.

**Comment by kromar** [comment]
this should be fixed in the latest master now, was not easy to find but easy to fix. thanks for reporting the issue!
