### ISSUE TITLE
Addon for blender 2.90 and zbrush 2021 does not work.

### ISSUE THREAD

**Issue by Igrom4ik** [JoseConseco/GoB#170]
There are no reactions - no errors and no export of the model to zbrush.

**Comment by kvmorgan** [comment]
I can confirm. I'm on OSX Catalina. I did a little digging, and it seems the .goz file is created, but zbrush never loads it. Also, if I run it and zbrush is already open, a second instance of zbrush is spawned.

**Comment by kromar** [comment]
i should get a mac this week so i should be able to  fix this soon. until then you could try to work with the latest release that should still work

**Comment by kromar** [comment]
please give this new version a try and let me know if you got any issues

v3.4.9
https://github.com/kromar/blender_GoB/tree/bugfix/fixmacos

**Comment by kvmorgan** [comment]
Excellent! I can round trip between blender and zbrush. And I don't get a second zbrush process launched. Along with my mesh, I'm getting a cube in the subtools going from blender to zbrush. Not a big deal, but it's there.

Thank you for your work on this!
