### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by LLKoder** [JoseConseco/GoB#171]
Hello,

When I save blend file I get some error:

> Traceback (most recent call last):
>   File "C:\Users\*******\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\GoB\GoB.py", line 817, in poll
>     numFaces = len(context.selected_objects[0].data.polygons)
> IndexError: list index out of range
> 
> location: <unknown location>:-1

If it helps I have one curve only in the scene.

Blender: 2.90
GoB:  3.4.8

**Comment by kromar** [comment]
interesting i will see if i can reproduce that

**Comment by LLKoder** [comment]
I have this bug everytime when I do any action (for ex. Copy/Paste or Save file, etc) although the Import button is off. I'm forced to turn off add-on every now and then.

**Comment by kromar** [comment]
@LLKoder i am not able to reproduce this issue, can you share a blend file where this hppens?

**Comment by LLKoder** [comment]
I have rolled back to Bender 2.83.6, there is the same problem. Before 2.90 I used 2.81 was ok.

> @LLKoder i am not able to reproduce this issue, can you share a blend file where this hppens?
Sure, I share blend file. It consists of blend file and screenshot. The action what I do at the screenshot - Save File.
[Blend file](https://drive.google.com/file/d/1cGGCHtrrv4oB81vlUkULQocF38WmBKph/view?usp=sharing)

**Comment by kromar** [comment]
hmm maybe, i do not get the error when saving that blend file and i do not see why that error would happen. make sure if you install the latest version again to delete the folder of the old addon.

**Comment by LLKoder** [comment]
I have updated the add-on. The bug is fixed. Perhaps, this bug was on my side only, idk. Any case, thanks for the help.
