### ISSUE TITLE
GOB export from Blender issue

### ISSUE THREAD

**Issue by imtomgamedev** [JoseConseco/GoB#172]
This is likely not a bug, just maybe setup error on my part.  I've successfully sent a subtool from Zbrush to blender.  When trying to export from Blender to Zbrush, it simply opens the "Blender File View" dialog box and nothing happens.  Any ideas?  BTW, I'm running on Mac.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/28981927/94061075-e10db780-fdb2-11ea-972e-f1cb684ffe42.png">

**Comment by tomimgamedev** [comment]
I did discover that changes I make to Blender meshes are saved to the GozProjects/Default folder.  It's just that there's a disconnect when exporting from Blender to Zbrush.  The updates are not being loaded into Zbrush and within Blender, the Blender File View dialog appears as mentioned in my original post.

**Comment by kromar** [comment]
hi @imtomgamedev it is a issue with the addon and mac, i got a mac 2 days ago and started looking into this so i will hopefully be able to fix this issue.

**Comment by imtomgamedev** [comment]
Awesome!  I'll watch for news.  Thanks, Kromar

**Comment by kromar** [comment]
please give this new version a try and let me know if you got any issues

v3.4.9
https://github.com/kromar/blender_GoB/tree/bugfix/fixmacos

**Comment by imtomgamedev** [comment]
I only quickly gave it a try.  Removed the prior addon and installed the updated one.  Here's my settings, maybe somethings not set correctly. 
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/28981927/94349784-f1719c80-0015-11eb-850d-4dd3a59370b7.png">
Same issue as before, see capture: 
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/28981927/94349799-149c4c00-0016-11eb-9616-822196c39577.png">

**Comment by kromar** [comment]
your input path is not correct it should include the ZBrush.app
try this:
/Volumes/EXT-APPS/Applications/ZBrush 2021.1.1/ZBrush.app

**Comment by imtomgamedev** [comment]
That seems to have possibly fixed the import issue, though, the captures below don't quite match what I was seeing in the YT video.  Rather than automatically placing the Blender object onto Zbrush's canvas as seen in the YT video, the exported object appears only when I click and drag onto the canvas.  Also, appears to include an additional subtool "Cube3D_1" that was not a part of my Blender object exported.  That said, it appears the addon is exporting and importing, just not sure about the initial export from Blender.

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/28981927/94361093-e4899300-007f-11eb-8838-c033db886d02.png">
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/28981927/94361249-ee5fc600-0080-11eb-9b15-835933d863f1.png">
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/28981927/94361274-08010d80-0081-11eb-89fe-f588344a7ea9.png">
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/28981927/94361280-0df6ee80-0081-11eb-80c9-7314207b1b8a.png">
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/28981927/94361312-426aaa80-0081-11eb-80f5-ae22d6909297.png">
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/28981927/94361316-4ac2e580-0081-11eb-8fda-7e3d280d33a2.png">

**Comment by kromar** [comment]
This is currently how it works. When you send over more objects they should be added as subtools. And the initial cube is a known issue but with low priority ti fix.

**Comment by imtomgamedev** [comment]
Glad to know it’s working now, thank you for help!  I’ll try and watch for updates to this add on, really like it.
