### ISSUE TITLE
Can't export mesh to Zbruhs from blender

### ISSUE THREAD

**Issue by Aurontwist** [JoseConseco/GoB#183]
Traceback (most recent call last):
  File "C:\Users\zsolt\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\GoB-master\GoB.py", line 1296, in execute
    self.exportGoZ(PATH_GOZ, context.scene, obj, f'{PATH_PROJECT}')
  File "C:\Users\zsolt\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\GoB-master\GoB.py", line 1079, in exportGoZ
    goz_file.write(pack('<H', groupColor[map.value]))  
IndexError: list index out of range

location: <unknown location>:-1

**Comment by kromar** [comment]
thanks for reporting the error, can you tell me what version you are using?

**Comment by Aurontwist** [comment]
> thanks for reporting the error, it would be good to get a bit more information to reproduce the error,
> can you tell me what version of the addon and the blender version you are using?
> The error seems to come from the Face Maps, can you share a screenshot of the GoB addon preferences so i see the configuration you are using?
> Of course if you are able to share the zbrush file or one where it happens would be the easiest to reproduce.

Operating system: Windows-10-10.0.18362-SP0 64 Bits
Graphics card: GeForce RTX 2080/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 452.06
Blender version: 2.90.1, branch: master, commit date: 2020-09-23 06:43, hash: `rB3e85bb34d0d7`

**Comment by kromar** [comment]
@Aurontwist this should be fixed in the latest master (v3.4.10) let me know if you have any other issues
https://github.com/JoseConseco/GoB
https://github.com/JoseConseco/GoB/archive/master.zip
