### ISSUE TITLE
path to blender is missing from zbrush>GoZ menu

### ISSUE THREAD

**Issue by mac4kent** [JoseConseco/GoB#185]
I am still not finish talk with you. 
Windows already have direct C:/>
Need to add note on Volumes / ... 
Because of ZBrush 2021 not have Blender GoB on Preferences.

**Comment by mac4kent** [comment]
![image](https://user-images.githubusercontent.com/4253305/96830540-6e631c80-13f0-11eb-8cfa-c1cab5984696.png)

**Comment by kromar** [comment]
ah yes i noticed this some time ago but forgot to look into this. thanks for reporting.

**Comment by mac4kent** [comment]
Goooooooooood

**Comment by mac4kent** [comment]
When will you make update let us know and I will get download again.

**Comment by Ozalynda** [comment]
This is precisely the problem I am having right now with Zbrush 2022.0.2
![image](https://user-images.githubusercontent.com/109141301/178453602-dab0e8e0-0d00-4732-b39e-1b513ac91956.png)

**Comment by ahingel** [comment]
i have the same issue. there is no path from zbrush to blender

**Comment by mac4kent** [comment]
> i have the same issue. there is no path from zbrush to blender
> 
> what should i do?

2 years ago is no long any more. There already fixed everything update recent. You will have to update zBrush 2022.xx plus Blender 3.3.1

Path is automatic without you do manual on path.
