### ISSUE TITLE
Errors when Exporting

### ISSUE THREAD

**Issue by phillipjpark** [JoseConseco/GoB#189]
Hello! I installed GoB and set the paths correctly to Blender but I keep getting this error. I installed a clean version of Gob and uninstalled and deleted old versions. Did I miss something?

<img width="540" alt="Screenshot_4" src="https://user-images.githubusercontent.com/52205460/98666100-d3a19200-234c-11eb-8cb3-363c9205f6cb.png">

**Comment by kromar** [comment]
please show the paths that are set in the addon preferences. Looks like some paths are not correct

**Comment by kromar** [comment]
please try to run the GoZ installer from zbrush and see if that solves the problem

![Screen Shot 11-02-20 at 10 19 PM](https://user-images.githubusercontent.com/1472884/98697035-bed8f480-2374-11eb-8134-f6d82455db1a.PNG)

**Comment by phillipjpark** [comment]
Thank you for the response! 
<img width="510" alt="Screenshot_1" src="https://user-images.githubusercontent.com/52205460/99066964-275ce700-25aa-11eb-8ec9-6c0bf9a98d58.png">
<img width="394" alt="Screenshot_2" src="https://user-images.githubusercontent.com/52205460/99066980-2b890480-25aa-11eb-8558-16ff9bcca192.png">
<img width="887" alt="Screenshot_3" src="https://user-images.githubusercontent.com/52205460/99066989-2e83f500-25aa-11eb-9d69-489af1ccd43c.png">


I'm on Windows 10. I did install the Goz form the Zbrush installer like you suggested, still getting errors. Here's the message plus the Window Console. I do have my Zbrush in my E Drive instead of the normal C drive (same with Blender).

**Comment by kromar** [comment]
![image](https://user-images.githubusercontent.com/1472884/99145215-335dad00-266d-11eb-882e-c27556c0748f.png)
can you set these paths to something valid and try again?

**Comment by phillipjpark** [comment]
Ah that solves it! I believe it was a combination of the installer and setting the zbrush project path (which i did b4 but not the gozinstaller). Thank you!!!
