### ISSUE TITLE
Can't export to zbrush :(

### ISSUE THREAD

**Issue by cyberhirsch** [JoseConseco/GoB#192]
Hi :)
![image](https://user-images.githubusercontent.com/50666797/100008006-2a877c80-2dcd-11eb-9ac6-587a7d55f957.png)
![image](https://user-images.githubusercontent.com/50666797/100008144-51de4980-2dcd-11eb-8a5a-40938abad827.png)
got the latest GoB-master.zip
Blender 2.90 / Zbrush2021.1.2

Any ideas?

**Comment by kromar** [comment]
can you try to run blender as admin? this looks like some account restriction issue

**Comment by cyberhirsch** [comment]
Yes, Sir! Thanks a lot!
