### ISSUE TITLE
Triangulate mesh while export.

### ISSUE THREAD

**Issue by koloved** [JoseConseco/GoB#193]
you need to triangulate the models when exporting otherwise the models have visual issues in zbrush.

https://i.postimg.cc/WzSyYTZX/Screenshot-6.jpg

**Comment by kromar** [comment]
@koloved can you provide a mesh where this happens? the mesh should be triangulated, i fixed this issue some time ago as far as i can remember.

what version of GoB are you using?

**Comment by kromar** [comment]
@koloved can you provide a mesh that causes this? i am not able to reproduce this issue.

**Comment by koloved** [comment]
i open the file again and export the mesh and i didnt get any issue, oh 

if i get any issues in the future i wlll let you know
