### ISSUE TITLE
Auto-convert bezier curves

### ISSUE THREAD

**Issue by koloved** [JoseConseco/GoB#194]
it need the plugin to automatically hiddenly convert curves to meshes when exporting

it can't be sent at all right now.

**Comment by kromar** [comment]
@koloved i implemented this in this branch it should support all types of bezier or nurbs curves and surfaces as well as Font and Meta objects.
Please let me know if you encounter any issues since it might be that i missed some things.

GoB v3.5.3
https://github.com/kromar/blender_GoB/tree/feature/test-addon-updates
https://github.com/kromar/blender_GoB/archive/feature/test-addon-updates.zip

**Comment by koloved** [comment]
oh great! Thank you! 
but i cant even enable the addon
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\kolov\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender_GoB-feature-test-addon-updates\__init__.py", line 53, in <module>
    addon_updater.BAU_OT_SearchUpdates,
AttributeError: module 'blender_GoB-feature-test-addon-updates.addon_updater' has no attribute 'BAU_OT_SearchUpdates'

**Comment by kromar** [comment]
do you have another version of GoB installed?

**Comment by kromar** [comment]
ah there was a typo in the operator name, strange that it worked for me

can you try the latest version v3.5.32
https://github.com/kromar/blender_GoB/tree/feature/test-addon-updates

**Comment by koloved** [comment]
oh yes ! its working ! works like a charm but i found an issue - 
look , when you'd use fill caps function  - 
[https://prnt.sc/xggxi9](https://prnt.sc/xggxi9)
you cant subdivide it - [https://prnt.sc/xgh0x5](https://prnt.sc/xgh0x5)
it should have to be merge by distance before exporting - 
[https://prnt.sc/xgh6tz](https://prnt.sc/xgh6tz)

**Comment by kromar** [comment]
i added this and also the nonmanifold option

![Screen Shot 01-23-21 at 09 01 PM](https://user-images.githubusercontent.com/1472884/105612829-cb3eec00-5dbe-11eb-84a8-3268f88757fd.PNG)


GoB v3.5.40
https://github.com/kromar/blender_GoB/tree/feature/test-addon-updates
