### ISSUE TITLE
Enabling the Addon in Blender 2.91 Throws Error 

### ISSUE THREAD

**Issue by bottledsmoke** [JoseConseco/GoB#195]
**OS**
MacOS Big Sur 11.0.1

**GoB Version**
Current Master (3.4.10)

**Blender Version**
2.91

**Zbrush Version**
2021.1.2

![Screen Shot 2020-11-29 at 1 01 01 PM](https://user-images.githubusercontent.com/7918530/100549812-3945b780-3243-11eb-892e-ab5c0f52c047.png)

**Issue**
When I enable the addon after installing it, Blender throws an error.

**Comment by kromar** [comment]
can you try this version (v3.4.11) and see if it solves your issue?
https://github.com/kromar/blender_GoB/tree/feature/fix-os-detection
https://github.com/kromar/blender_GoB/archive/feature/fix-os-detection.zip

**Comment by bottledsmoke** [comment]
![Screen Shot 2020-12-12 at 12 56 49 AM](https://user-images.githubusercontent.com/7918530/101976641-2359ce80-3c15-11eb-864c-8799ab808a1c.png)

Still throwing an error, but it's a new one now.

**Comment by kromar** [comment]
can you try this one v3.4.12

https://github.com/kromar/blender_GoB/tree/feature/fix-os-detection
https://github.com/kromar/blender_GoB/archive/feature/fix-os-detection.zip

**Comment by bottledsmoke** [comment]
![Screen Shot 2020-12-12 at 12 53 27 PM](https://user-images.githubusercontent.com/7918530/101991186-0b1b9b00-3c79-11eb-90ea-c643655ae2a6.png)

We're getting there. Now "Local Variable PATH_GOZ referenced before assignment."

**Comment by kromar** [comment]
can you give this a try? there was some leftover path checking which is no longer used, lets see if that brings us furhter
v3, 4, 13

https://github.com/kromar/blender_GoB/archive/feature/fix-os-detection.zip

**Comment by bottledsmoke** [comment]
Exporting to ZBrush and importing to Blender both work now. Thank you so much :)
