### ISSUE TITLE
Clean installation brings error when first pressing "export" - Windows

### ISSUE THREAD

**Issue by MattFagan** [JoseConseco/GoB#198]

**Comment by MattFagan** [comment]
![image](https://user-images.githubusercontent.com/18077806/102968327-7ef34a00-44a8-11eb-9fa6-d52b95911edb.png)

**Comment by kromar** [comment]
can you try to run the goz installer which can be found in the zbrush troubleshooting folder and see if it fixes the issue?
![image](https://user-images.githubusercontent.com/1472884/103038760-8b8ea580-456f-11eb-98f0-70cb92b0eeb6.png)

**Comment by MattFagan** [comment]
@kromar That fixed it! (Thank you!) - Note: I had removed "all" pre-existing files before running it, after re-installing it cleanly. That did the trick! Cheers

**Comment by kromar** [comment]
@MattFagan which pre existing files did you need to remove?

**Comment by chungking2399** [comment]
I got a trackback error as well
![err](https://user-images.githubusercontent.com/63893089/105232773-7edd7d00-5b2e-11eb-9f3b-26abcef604ba.jpg)

**Comment by kromar** [comment]
hm i think i seen this before and thought i made a fix for this. Can you try to run blender in administrator mode? if that works there seems to be some issue to run the zbrush script from blender.

**Comment by kromar** [comment]
i added a potential fix in a experimental version, would be great if you can try if that works for you.

GoB v3.5.32
https://github.com/kromar/blender_GoB/tree/feature/test-addon-updates
https://github.com/kromar/blender_GoB/archive/feature/test-addon-updates.zip

**Comment by chungking2399** [comment]
ok thank you so much, will set it up right now

**Comment by chungking2399** [comment]
That WORKED Thank you
