### ISSUE TITLE
Create branch for Blender 2.80 version

### ISSUE THREAD

**Issue by moppius** [JoseConseco/GoB#2]
I noticed that you have offered a 2.80 version for download on your blog. Maybe it can also be added to this repo as a branch, or tag the current version for reference and overwrite the script with the newer one?

It would be nice to have this as a central resource for improving the state of the tools, since it's GPL-licensed anyway, it seems like a good idea to have a public repo instead of people just sharing zip files in random forum threads and websites.

**Comment by moppius** [comment]
Now I think about it, might be better just to have the `GoB_2-80.py` file in the *master* branch alongside the `GoB_2-79.py` version.

I don't know how to do it yet, but this method seems to be used for the appleseed Maya plugin - they have a Releases page on GitHub with download links for different versions, which is pretty cool: https://github.com/appleseedhq/appleseed-maya/releases

I'll look into how to set this up a bit, it'd be nice to have a consistent release mechanism.

**Comment by JoseConseco** [comment]
DOne
