### ISSUE TITLE
DynaMesh Utillity destroys object with applied modifier array

### ISSUE THREAD

**Issue by PoloxDisc** [JoseConseco/GoB#205]
Before modifiers:
![image](https://user-images.githubusercontent.com/28192518/104177410-00cff680-5409-11eb-9924-e6e2e8ba34be.png)
After modifieres:
![image](https://user-images.githubusercontent.com/28192518/104177460-1513f380-5409-11eb-86c1-4e3efe4fb043.png)
After importing to zbrush:
![image](https://user-images.githubusercontent.com/28192518/104177508-2d840e00-5409-11eb-945e-4483d5994421.png)
After DynaMesh Utillity:
![image](https://user-images.githubusercontent.com/28192518/104177615-5ad0bc00-5409-11eb-9d6a-29d77b98fc48.png)
Any idea how to solve this?

**Comment by kromar** [comment]
it seems to happen because the objects do not have a polygroup. if you auto generate some polygroups it should work.

**Comment by PoloxDisc** [comment]
Thank you buddy
