### ISSUE TITLE
issue with scaling when blender unit scale changes?

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#207]

**Comment by koloved** [comment]
yes i have this issue , i want to report it but you find it first

6 cm in zbrush = 60 meters in blender , the different is 1000 times 

if you want to fix it you should make "fake" sending , i mean when you press export or import you can automatically change the size in background
[https://prnt.sc/1128fi3](https://prnt.sc/1128fi3)

**Comment by kromar** [comment]
@koloved are you able to reproduce this issue? i have only encountered it once and was not able to reproduce it later on that is why i did not fix it.

**Comment by koloved** [comment]
GREAT! in blender the size is right ! thank you! 
but in zbrush its still 2mm instead of 2 meters 

correct size in zbrush is useful for people who use 3d printing 

https://prnt.sc/113f6fu

**Comment by kromar** [comment]
since you can set that unit in zbrush to anything you want i can not fix that. I am sending it in zbrush units, so 1m in blender should be 1 zbrush unit 

![image](https://user-images.githubusercontent.com/1472884/113490819-ec157300-94cc-11eb-848e-faf3c2d26588.png)


if you want some manual scaling there are options in the preferences to change that but it might not work for what you try to do
![image](https://user-images.githubusercontent.com/1472884/113490851-15360380-94cd-11eb-840d-231372b042de.png)

**Comment by kromar** [comment]
you can use the set scale to change the zbrush scale calibration
![image](https://user-images.githubusercontent.com/1472884/113490906-5c23f900-94cd-11eb-87c4-422414b21ce8.png)
