### ISSUE TITLE
An error occurred when importing ZB,but model in gozporject 

### ISSUE THREAD

**Issue by akuasama** [JoseConseco/GoB#211]
Python: Traceback (most recent call last):
  File "C:\Users\Akua\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\GoB-master\GoB.py", line 1486, in execute
    bpy.ops.gob.find_zbrush()
  File "D:\SteamLibrary for software\steamapps\common\Blender\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: 错误: Python: Traceback (most recent call last):
  File "C:\Users\Akua\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\GoB-master\GoB.py", line 1466, in execute
    i,zfolder = max_list_value(os.listdir(self.filepath))
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:/Program Files/Pixologic/'

location: D:\SteamLibrary for software\steamapps\common\Blender\2.91\scripts\modules\bpy\ops.py:132

location: <unknown location>:-1

**Comment by kromar** [comment]
can you tell me where you installed zbrush?

**Comment by akuasama** [comment]
> 你能告诉我你在哪里安装的 zbrush 吗？

D:\zbrush2021  my zbrush versions is 2021

**Comment by kromar** [comment]
Thanks for sharing, it seems i did not considee custom zbrush paths when changing the option. You can try to set the zbrush.exe manually in the addons preferences.

**Comment by kromar** [comment]
can you try this version and see if it solves the issue for you? if you have a custom path and the addon cant find zbrush in its default installation path it should navigate you to the addon preferences where you should specify your custom zbrush path. 

![Screen Shot 02-08-21 at 06 25 PM](https://user-images.githubusercontent.com/1472884/107258336-f589de00-6a3b-11eb-91fb-b213fce1887a.PNG)
![image](https://user-images.githubusercontent.com/1472884/107258295-ec990c80-6a3b-11eb-9f3f-3a939a1096c5.png)

after you specified the path you should save the preferences (if autosave is not enabled)

GoB v3.5.45
https://github.com/kromar/blender_GoB/tree/bugfix-zbrush-path-issues
https://github.com/kromar/blender_GoB/archive/bugfix-zbrush-path-issues.zip

**Comment by akuasama** [comment]
oh~thank you~

**Comment by akuasama** [comment]
I'm sorry for not replying in time .The problem has been solved  Thank you very much
