### ISSUE TITLE
Can't export from Blender to Zbrush

### ISSUE THREAD

**Issue by nanami773ito** [JoseConseco/GoB#213]
click the export button in blender and pops up this:
![7ZMA)QFN18UB6WCG832`$O5](https://user-images.githubusercontent.com/79393913/108617786-08e17400-7454-11eb-813d-f095c7b3a012.png)

then go to zbrush is like this:
![04QBLBJHKD~DQEM8QW { `8](https://user-images.githubusercontent.com/79393913/108617784-054ded00-7454-11eb-9694-d94d63c568f5.png)

Import from Zbrush to Blender works fine.

**Comment by kromar** [comment]
please try this version and see if it solves your issues

GoB v3.5.45
https://github.com/kromar/blender_GoB/tree/bugfix-zbrush-path-issues
https://github.com/kromar/blender_GoB/archive/bugfix-zbrush-path-issues.zip

**Comment by nanami773ito** [comment]
there is no more error, but still have some issues
export with blender only add a bunch of polymesh3d stars to zbrush
I found that if I import something from zbrush first, and then re-export, it will work
so my workaround is export with an obj file, then import from zbrush to blender and split into several pieces,
then export again, it's fine, just a little extra work.
anyway, thanks a lot!

**Comment by kromar** [comment]
that does not sound right and i have never seen or heard of such a issue before. can you please check if you get any errors in the console?
also what blender and zbrush versions are you using?
do you have some custom installation or project paths or change any of the preferences in the addon?
