### ISSUE TITLE
GoB Addon not allowing to activate

### ISSUE THREAD

**Issue by RosieDavis** [JoseConseco/GoB#214]
Hi All. I attempted to install GoB v3_5_1 addon but I keep getting this message. I copy and extracted GoB v3_5_1 and renamed it GoB and addded the folder into my Blender addon folder located in  "C:\programs files\ Blender foundation\Blender\2.79\scripts\addons" I restarted Blender and went into user preferences but when I try to make the addon active I get this error:
![Addon Traceback Error 2021-02-26_13-13-52](https://user-images.githubusercontent.com/79719565/109351161-66a00280-783e-11eb-9e73-b214806e4c76.png)

What did I miss?

**Comment by kromar** [comment]
Hi, this version of the addon requires blender 2.83+

you can get the old version for blender 2.79 here:
v2.1.0
https://github.com/JoseConseco/GoB/tree/GoZ-Blender-279
https://github.com/JoseConseco/GoB/archive/GoZ-Blender-279.zip

**Comment by RosieDavis** [comment]
Thank you Sir, that resolved it.

**Comment by RosieDavis** [comment]
Thanks those worked.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
