### ISSUE TITLE
Overlap after click Export button on top

### ISSUE THREAD

**Issue by mac4kent** [JoseConseco/GoB#217]
Blender 2.93 Alpha
Overlap after click Export need to fix width on your GoB
See picture 
![image](https://user-images.githubusercontent.com/4253305/109434450-3f763c00-79ca-11eb-9865-f652d9261755.png)

Because of large text on Preferences
1. Edit > Preferences >> Interface tab and change 2.00 (resolution Scale)
2. Edit > Preferences >> Themes tab and click Text Style then change from 12 to 24 (all of them "Points")

**Comment by kromar** [comment]
this should fix the issue, the popup should scale with the font size. would be great if you can confirm that it works for you.

https://github.com/kromar/blender_GoB/tree/feature/fix-popup-overlap-with-ui-scale

**Comment by mac4kent** [comment]
Yaaaa ay it work 
![image](https://user-images.githubusercontent.com/4253305/110047527-e62c4680-7d02-11eb-9f23-eefd203d5d00.png)

**Comment by mac4kent** [comment]
Let's close the ticket
