### ISSUE TITLE
Modifiers not applied on 3.5.45, apply and export error

### ISSUE THREAD

**Issue by fusobotic** [JoseConseco/GoB#223]
Using Blender v2.83.12 (LTS) and ZBrush 2021.5. Mesh will show up in ZBrush but does not have the modifiers "Only Export" applied, there is not error that I can see in the console:
![image](https://user-images.githubusercontent.com/9371787/110652383-50713b00-818a-11eb-93f9-a909483cedba.png)

Switching to "Apply and Export" returns an error though:
![image](https://user-images.githubusercontent.com/9371787/110652751-a6de7980-818a-11eb-89b4-7cc71c9c1093.png)

Reverting to 3.5.1, the issue is not present. Would love to have this fixed since I really appreciate the curves export feature but am reliant on modifiers a lot.

**Comment by kromar** [comment]
hi, thanks for reporting the issue.
Can yo give this version 3.5.49 a try and see if it works again for you? 
https://github.com/kromar/blender_GoB/archive/refs/heads/bugfix/fix-apply-modifier.zip

**Comment by fusobotic** [comment]
Yeah that new release seems to be working. Still using the same versions of Blender/Zbrush as I initially said. I'll let you know if I run into anything else. Thanks!
