### ISSUE TITLE
When  zbrush subtool has scale factor send to blender  and reback to zbrush  the scale factor will change to 1 

### ISSUE THREAD

**Issue by 879096600** [JoseConseco/GoB#226]
When  zbrush subtool has scale factor send to blender  and return to zbrush  the scale factor will change to 1 ,so other subtools become 2mm size   .

**Comment by kromar** [comment]
@879096600 can you try if this version fixes your scaling issue?
https://github.com/kromar/blender_GoB/tree/bugfix/scaling-with-blender-units

if not then it would be great to get a bit more details on what you are doing so i can reproduce the issue.
