### ISSUE TITLE
Path failed in second export (MacOS)

### ISSUE THREAD

**Issue by Odin3D** [JoseConseco/GoB#230]
Hi, I use gob without problems the first time, but when doing a new export the addon adds zbrush.app and gives an error. I have to delete the text from zbush.app and save so that it can export properly. It only happens to me in macos.
![Captura de pantalla 2021-04-07 a las 11 16 25](https://user-images.githubusercontent.com/82088076/113842745-45aec380-9793-11eb-8bb4-2845a6d3dd6b.png)
![Captura de pantalla 2021-04-07 a las 11 17 05](https://user-images.githubusercontent.com/82088076/113842749-46475a00-9793-11eb-940a-04f154c7ee5d.png)
![Captura de pantalla 2021-04-07 a las 11 16 55](https://user-images.githubusercontent.com/82088076/113842747-46475a00-9793-11eb-94a0-46bfa57bf807.png)

**Comment by kromar** [comment]
hi @Odin3D did you try the lastest release? https://github.com/JoseConseco/GoB/releases/tag/v3_5_50
this should have been fixed in that version
