### ISSUE TITLE
zbrush 2021.6.2 export not working

### ISSUE THREAD

**Issue by fislysandi** [JoseConseco/GoB#231]
when the addon will support this version?

**Comment by kromar** [comment]
is there something specific that is not working for you? i am not aware of anything that should not be working with that version.

**Comment by fislysandi** [comment]
oh its working i just forgot to drag n drop the zscript into zbrush sorry but i have the other issue to report when i switch the settings on export from export only to export and apply this happens https://imgur.com/a/3ATrAhz basically export with applying modifs not working.

**Comment by kromar** [comment]
sorry what script did you drag into zbrush? there should be no need to do anything other than installing the addon and start sending meshes to zbrush.
the modifiers are a known issue and should be fixed soon.

**Comment by kromar** [comment]
i made a fix for applying the modifiers, would be great if you could give it a try

v3.5.51
https://github.com/kromar/blender_GoB/tree/bugfix/apply-modifiers
