### ISSUE TITLE
GoB Mantaflow Bug

### ISSUE THREAD

**Issue by hdharris** [JoseConseco/GoB#243]
When GoB is enabled, it IMMEDIATELY causes a full crash upon hitting bake data in mantaflow I went through and methodically disabled and renabled add-ons and determined specifically that it is GoB causing this issue.

I am using an AMD 3900x cpu, an rtx 2080, 32gigs of ram, if that is at all relevant

**Comment by kromar** [comment]
i have been able to create some blender crashes but not related to the addon. Can you provide a blend file that causes that crash you describe?

**Comment by hdharris** [comment]
of course, for reference, 

I loaded factory settings, enabled GoB, set up a basic mantaflow sim to bake with default settings, hit bake and it instantly crashed.
[Bug Test.zip](https://github.com/JoseConseco/GoB/files/6594466/Bug.Test.zip)

**Comment by kromar** [comment]
thanks, i can reproduce the crash. i will have a look if i can fix it

**Comment by hdharris** [comment]
Thank you for your time and efforts looking into it, the addon is essential and I'm so glad it exists!

**Comment by kromar** [comment]
i have been able to find the cause of the crash but im not sure how to fix it yet. can you tell me if you send baked fluids over to zbrush or if that is something you would do? if i get a better understanding how you use them it might be easier to make a good fix for the crash.

**Comment by hdharris** [comment]
I was just trying to bake them in blender, I didn't intend to send them anywhere else, but I couldn't get them to start at ALL. Oddly, they would play in replay, but once I turned the setting to modular or All and tried to bake, instant crash.

**Comment by kromar** [comment]
oh i think i forgot to report back to you. I disabled the checks ive done to avoid the crash when baking. Let me know if you get some other issues with this version.
https://github.com/JoseConseco/GoB/releases/tag/v3_5_56

**Comment by hdharris** [comment]
oh great! i'll test this out!

**Comment by hdharris** [comment]
It works! thank you so much!
