### ISSUE TITLE
request /issue

### ISSUE THREAD

**Issue by unrealghys** [JoseConseco/GoB#245]
due to the custom shelf, I cannot access the shelf command there is a way to call them by terminal script or any other way? 

thx =)

**Comment by kromar** [comment]
sure, you should be able to find it in the search function.
bpy.ops.scene.gob_export()

![image](https://user-images.githubusercontent.com/1472884/122675183-92be0580-d1d8-11eb-96b8-77f3f9136215.png)

can i ask what that custom shelf is?

**Comment by unrealghys** [comment]
thank you !  yesterday I manage to find one shelf not touched by it and I found the button but with this call, I can add it to another shelf and call it from it! the shelf is from form affinity Maya config. I`m trying to switch to Blender after years of Maya so I needed an easier transition.
