### ISSUE TITLE
GoB Export Options "Vertex Merging" does not seem to work. (And request for disable.)

### ISSUE THREAD

**Issue by Tsukasa-YAMATO** [JoseConseco/GoB#247]
Long time no see. This is a bug report for GoB release version Ver.3.5.52. Vertex Merging feature does not seem to work. Please check it.
And I don't want GoB addon to change the topology so please add a checkbox for enable/disable this feature.

Thank you.

My environment
Windows 10 Pro
Blender 2.92.0
GoB Ver.3.5.52

![2021-07-01_20h13_42](https://user-images.githubusercontent.com/65609416/124116897-73618b00-daaa-11eb-970c-140be45bee48.png)

**Comment by kromar** [comment]
hi, this is only used when working with surface type objects like curves and it does not apply to mesh objects. This is probably why its not doing anything for you.
Its very unclear from the ui and i had to go into the code to see that so i will do some changes to the ui to reflect the usage of this.

**Comment by Tsukasa-YAMATO** [comment]
I was relieved to hear the vertices of the mesh object will not be  merged and the topology will not be changed.
As you say, it's enough if you add sufficient explanation to the popup help description.

**Comment by kromar** [comment]
merged some changes to master, should be version 3.5.53
