### ISSUE TITLE
tags can not contain dots (blender addon loading)

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#25]
the tags break the release installation again, they can not contain dots or blender can not load the addon.

not sure if how the updater will handle tags without dots, that is something that needs to be tested.

**Comment by JoseConseco** [comment]
But the releases alway had dots in names. So now it should be changed from:
v3.0.2  to => v302 ?

**Comment by kromar** [comment]
well in that case the releases probably never worked with blenders install option.
i think anything without the dots should work, not sure if something like underlines (v3_0_2) would work for the updater.
i think we should test if the new tags are also working for the updater.

**Comment by JoseConseco** [comment]
According to:  [https://medium.com/cg-cookie/blender-updater-tutorial-3509edfc442](https://medium.com/cg-cookie/blender-updater-tutorial-3509edfc442)
it should work the way it is now.
v3.0.1 or 3.0.1 .  
Sorry I can't take time to dive into autoupdater. It is to bigg - bigger and more complicated than the addon itself.

**Comment by kromar** [comment]
i can do some testing on the tags as i already added some debug output to the version parsing of the updater.
yes it works with the dots but i want to have a look what happens with a tag that has no dots since we need that so the releases dont contain dots.

**Comment by JoseConseco** [comment]
Ok here it is: https://github.com/JoseConseco/GoB/releases/tag/v305

**Comment by kromar** [comment]
i had a look and the updater compares the bl_info: version which has the dots inside so i will need to do some changes there to convert the version string.

im at a point where i question the updater implementation, it seems to cause quite some maintenance not to mention what will happen if we want to update to a new updater version.

what do you think, should we remove the updater for the time being until they make it a real module that does not need to be implemented in such a tedious way?

**Comment by JoseConseco** [comment]
I'm ok with removing autoupdater. It is to big for me to dig in. 
For my private addons I have made way simpler updater script, but it dosen't support GitHub. 
You may want to report bug to the author of script (CG Cookie?), if you have want. Maybe they will fix it.

**Comment by kromar** [comment]
im in contact with them so lets see what comes out of it

**Comment by kromar** [comment]
@JoseConseco hey i did some more testing and it turns out we can use _ instead of . in the tags, that works with the version parsing of the updater and should also work with the releases since there are no dots in the version.
can you replace all the tags with this scheme? v3_0_4

**Comment by JoseConseco** [comment]
Ok. Done. Let me know if that works

**Comment by kromar** [comment]
![image](https://user-images.githubusercontent.com/1472884/58628333-b3595100-82d9-11e9-8805-32b3705ae748.png)
its a mess currently with the tags

**Comment by JoseConseco** [comment]
Ok, my bad. I find edition bit confusing. SHould be ok now

**Comment by kromar** [comment]
the tags no all point to the same commit 
![image](https://user-images.githubusercontent.com/1472884/58630193-f538c600-82de-11e9-83b1-2843af883493.png)

**Comment by kromar** [comment]
![image](https://user-images.githubusercontent.com/1472884/58630320-53fe3f80-82df-11e9-9eef-8bbabb720312.png)
here are the hashes where the tags have been before, maybe you can give me collaboration rights on this repo, it would make things a bit easier for me^^

**Comment by JoseConseco** [comment]
I was just removing tags, from github, not sure why they point to same point. I have sent you invitation. 
I can remove all tags, and just make new release. This should clean things up.

**Comment by kromar** [comment]
i created new tags pointing to the original commits, thanks for the invite^^
