### ISSUE TITLE
Mismatched description in the Zscript GoB_Import.txt

### ISSUE THREAD

**Issue by Tsukasa-YAMATO** [JoseConseco/GoB#250]
In GoB_Import.txt, I feel that the content of the comment, the list number, and the actual variable passing do not match.

Please check it out once.

![ZscriptMistake](https://user-images.githubusercontent.com/65609416/124549755-943f2d00-de6a-11eb-8c00-a3591925ebb7.png)

Should the "0: object name" item in the comment be removed? And the numbers should shift.

Therefore, it will be necessary to correct the 16th to 23rd lines.

(This may be useful.)
![DefVar](https://user-images.githubusercontent.com/65609416/124553208-6dcfc080-de6f-11eb-992c-49b147c2fd17.png)

**Comment by kromar** [comment]
its just the comment that has not been updated when the variables changed. 
if you look at line 696 in GoB.py you see what is written into the file.

`
# write GoB ZScript variables
        variablesFile = f"{PATH_GOZ}/GoZProjects/Default/GoB_variables.zvr"        
        with open(variablesFile, 'wb') as GoBVars:            
            GoBVars.write(pack('<4B', 0xE9, 0x03, 0x00, 0x00))
            #list size
            GoBVars.write(pack('<1B', 0x07))   #NOTE: n list items, update this when adding new items to list
            GoBVars.write(pack('<2B', 0x00, 0x00)) 

            # 0: fileExtension
            GoBVars.write(pack('<2B',0x00, 0x53))   #.S
            GoBVars.write(b'.GoZ')
            # 1: textureFormat   
            GoBVars.write(pack('<2B',0x00, 0x53))   #.S
            GoBVars.write(b'.bmp') 
            # 2: diffTexture suffix
            GoBVars.write(pack('<2B',0x00, 0x53))   #.S            
            name = prefs().import_diffuse_suffix
            GoBVars.write(name.encode('utf-8'))    
            # 3: normTexture suffix
            GoBVars.write(pack('<2B',0x00, 0x53))   #.S
            name = prefs().import_normal_suffix
            GoBVars.write(name.encode('utf-8'))   
            # 4: dispTexture suffix
            GoBVars.write(pack('<2B',0x00, 0x53))   #.S
            name = prefs().import_displace_suffix
            GoBVars.write(name.encode('utf-8')) 
            #5: GoB version   
            GoBVars.write(pack('<2B',0x00, 0x53))   #.S         
            for mod in addon_utils.modules():
                if mod.bl_info.get('name') == 'GoB':
                    version = str(mod.bl_info.get('version', (-1, -1, -1)))
            GoBVars.write(version.encode('utf-8'))
            # 6: Project Path
            GoBVars.write(pack('<2B',0x00, 0x53))   #.S
            name = prefs().project_path
            GoBVars.write(name.encode('utf-8')) 

            #end  
            GoBVars.write(pack('<B', 0x00))  #. 
                 `

**Comment by kromar** [comment]
i updated the comments and merged it back to the master, so in v 3.5.54 should be the correct comments. thanks for pointing it out.

**Comment by Tsukasa-YAMATO** [comment]
Thank you for fixing it immediately.
There is no problem with the behavior because it's the comment part, but if there is a contradiction, it will be misunderstood when someone reads it later, so I thought it would be safer to unify it.

Please close this issue.
