### ISSUE TITLE
to get this to work I had to install this

### ISSUE THREAD

**Issue by spiraloid** [JoseConseco/GoB#26]
the doc was missing the following to get it to work.

first install the GoB addon for blender and activate.

then re-install GoZ for Zbrush from here:
C:\Program Files\Pixologic\ZBrush 2019\Troubleshoot Help\GoZ_for_ZBrush_Installer_WIN.exe

then launch ZBrush 2019.1 and run GoZ once and choose your blender install location.

then everything works.  you might want to update the readme.

**Comment by JoseConseco** [comment]
ok, I updated the docs.
