### ISSUE TITLE
README.md lacks ZBrush-side installation guide

### ISSUE THREAD

**Issue by aryez91** [JoseConseco/GoB#261]
Only blender-side installation is explained...

Finally got it from askNK. I suggest editing in --->
"Put GoB-X_X_XX\Blender folder under C:\Users\Public\Pixologic\GoZApps"

**Comment by kromar** [comment]
If GoZ is installed on zbrush side you should not need to copy anything manually, however you need to do the first transfer from blender to zbrush so those files that are required get installed for zbrush.
