### ISSUE TITLE
zbrush path 

### ISSUE THREAD

**Issue by rodrigotrovao** [JoseConseco/GoB#262]
when installing first time (version3.5.52), address shows like this :
C:/Program Files/Pixologic\ZBrush 2021\ZBrush.exe

**Comment by kromar** [comment]
is there something wrong with that?

**Comment by rodrigotrovao** [comment]
it doesnt install

Em sex., 10 de set. de 2021 às 03:25, Daniel G ***@***.***>
escreveu:

**Comment by kromar** [comment]
what does not install? it would help if you give a bit of context what you try to do and what does not work.

**Comment by rodrigotrovao** [comment]
When the address is wrong it doesn't install into zbrush. Inside zbrush,
'blender option' for gob does not shows.
When I fix it manually it installs.


Em sáb., 11 de set. de 2021 07:09, Daniel G ***@***.***>
escreveu:

**Comment by kromar** [comment]
what version of Gob are you using? it should ask you for a valid zbrush path if the default one is not working.
can you tell me your zbrush installation folder?

**Comment by rodrigotrovao** [comment]
it works if i change "/" this to "\"
but some users my not know. Thats why i sent this message.
just trying to help you and other users. For me, its working, because i
changed my address manually.
It was the same last 2 versions. This time, i sent a message about it.

version:
[image: image.png]

path:
"C:\Program Files\Pixologic\ZBrush 2021\ZBrush.exe"



Em sáb., 11 de set. de 2021 às 18:08, Daniel G ***@***.***>
escreveu:

**Comment by kromar** [comment]
ah ok, i thought i fixed all those backslashes. thanks for reporting this issue, i was not aware that is a issue.

**Comment by kromar** [comment]
can you give this version a try and let me know if you get any further issues?

GoB v3.5.59
https://github.com/kromar/blender_GoB/tree/fix-filepaths
https://github.com/kromar/blender_GoB/archive/refs/heads/fix-filepaths.zip

**Comment by rodrigotrovao** [comment]
Yes, it works! You made it.

[image: image.png]

After installation:
[image: image.png]


Em sáb., 11 de set. de 2021 às 19:31, Daniel G ***@***.***>
escreveu:

**Comment by kromar** [comment]
cool! thanks for testing and reporting the issue. let me know if you run into any other issues.
