### ISSUE TITLE
Error message in Blender 3.0 alpha (Sculpt Dev build)

### ISSUE THREAD

**Issue by MetinSeven** [JoseConseco/GoB#264]
Hi @kromar ,

After installing the latest GoZ for Blender in (the Sculpt Dev build of) Blender 3.0 alpha, I get this error message when trying to export a scene from Blender:

```
Python: Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\GoB-3_5_56\GoB.py", line 1252, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.scene.gob_export.poll() failed, context is incorrect

location: <unknown location>:-1
```

**Comment by MetinSeven** [comment]
It turned out that I hadn't selected objects yet. 😊 If it's possible, a message stating that would be welcome.

**Comment by nameless667** [comment]
So in your case, you are able to use GoB on 3.0 without your blender crashing?

**Comment by MetinSeven** [comment]
Yes, as long as I select objects first.

**Comment by kromar** [comment]
turns out this is not a 3.0 issue, it would happen when no objects are selected and the export is used. now the button should be disabled when no object is selected that can be exported.

v3.5.60
https://github.com/kromar/blender_GoB/tree/avoid-invalid-export-context
