### ISSUE TITLE
zbrush strips object names on import

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#267]

**Comment by kromar** [comment]
@blessedcoolant @nameless667

there was some problem in the renaming changes that i did recently. I noticed that zbrush has a limitation when it comes to suffix patterns, especially a .0 and i added a option to insert a string to fix this as zbrush does not seem to have issues with suffixes that follow with a letter after a dot.
You will need to enable this Raw Object Names options to use the new method. Otherwise the . will be replaced with a underline as its been doing for a long time before i broke it^^
![image](https://user-images.githubusercontent.com/1472884/134817158-a7e0c13d-fc0b-40df-9469-b8163b176a0b.png)

v3, 5, 62
https://github.com/kromar/blender_GoB/tree/fix-renaming

**Comment by nameless667** [comment]
Hey Daniel! thank you so much for your amazing work on this! I seem to be missing the "Fix Suffix" box, is this feature implemented in 3.5.64 ?  Also, just in case you are interested in things like these, there is a typo in the Experimental Versions tickbox at the bottom- it's missing an s. Again, much appreciation for the development!

**Comment by blessedcoolant** [comment]
Would like to add to what @nameless667 said. The fix name feature is missing from the latest build on your repo. I think when you merged it with the main version, you did not merge this change: https://github.com/kromar/blender_GoB/commit/4fd67de27ae8ade53f13e595e6e489e45d2bf23d#diff-62ca61fb6fb9797d8adc27c41ca82a0e4a025104742083520cb15b991ed93dcc

I manually added these to my version and the option shows up.

For some reason auto-import isn't working anymore on this build. But no crashes.

**Comment by blessedcoolant** [comment]
Sorry but another thing: a small feature request really ---- Can the addon be made to remember our preferences settings? It's a little bit frustrating to update the preferences settings every time we-reinstall / update a version.

**Comment by kromar** [comment]
I removed the option for the fix in the last comit since its no linger required, the code will handle the situation.

The preferences should be saved, i dont know why you would lose the preferences unless you start blender from visual studio
