### ISSUE TITLE
periodical import crashes blender

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#27]
hey there have been some reports that blender is crashing in the latest versions when a object is imported from zbrush. 
it seems that the periodical import somehow causes this but i could not figure out why since i cant trace the error. maybe you can have a look at this issue.

**Comment by koloved** [comment]
I have got the crash when i press GOZ twice

**Comment by Phardbean** [comment]
So far, for me, I only crash when I trying to go back to Blender. 13.6.2019 build. The funny thing though, when I reopen and only click on the import button it pops in.

**Comment by JoseConseco** [comment]
Fixed in 3.0.5. Timers are causing problems, so I had to revert them back to Modal Timer operator.
Maybe timers context will be fixed in blender someday. Then, we can revert this change. Bugs to watch:
https://developer.blender.org/T62051
https://developer.blender.org/T62074

**Comment by Phardbean** [comment]
> Fixed in 3.0.5. Timers are causing problems, so I had to revert them back to Modal Timer operator.
> Maybe timers context will be fixed in blender someday. Then, we can revert this change. Bugs to watch:
Thanks for the quickfix. =)
