### ISSUE TITLE
(ZScript) Interface item could not be found

### ISSUE THREAD

**Issue by Tianesus** [JoseConseco/GoB#270]
Hello, I am using Blender 2.93.4 and ZBrush 2021.7.1, and I'm having issues setting up the export from Blender to Zbrush, as I'm getting this error within ZBrush whenever hitting Export.

![image](https://user-images.githubusercontent.com/5891260/139598206-65b7828a-54ee-4569-9ba9-929e9c40d56c.png)

I'm noticing the .GoZ files get created and they are manually openable, but something in the script seems to not be working out, although this could very well also be user error.

**Comment by kromar** [comment]
try to run the GoZ installer and see if it resolves the issue
![blender_URuq2Z2AdB](https://user-images.githubusercontent.com/1472884/139599055-c4dac6be-f6b8-4e6e-ad41-be9aef9e181a.png)

**Comment by Tianesus** [comment]
I have, no luck so far

**Comment by kromar** [comment]
can you describe the exact steps you do to run into this issue?

**Comment by Tianesus** [comment]
The GoB version is 3.5.61

I have just attempted a fresh install of the plugin as well to be sure, so starting from that I've set up my ZBrush path (In case it's worth noting, it is not in the default C Drive directory) and my Project path. Re-installed GoZ once more using the extension, then tried to export the default Blender cube into ZBrush, leading to that same error

**Comment by kromar** [comment]
can you try the latest master? i did some changes in earlier versions that broke some filepaths

**Comment by Tianesus** [comment]
Updated to latest

![image](https://user-images.githubusercontent.com/5891260/139601151-cf911de9-87ae-4001-adbe-8148255a1b7d.png)
 sadly I'm still getting that same error

**Comment by kromar** [comment]
did you try to use the GoZ export on zbrush? maybe something with the initialization went wrong and you need to clean the settings to recover. 
![ZBrush_ZmBRhT7WJD](https://user-images.githubusercontent.com/1472884/139725497-e7a86fe2-64cf-4c2f-92de-d4879b76bda0.png)
![ZBrush_dFexebul17](https://user-images.githubusercontent.com/1472884/139725594-2c46a846-041b-4b38-b608-ff1e0b317957.png)

clear the cache, then restart zbrush and GoZ a tool from zbrush, this should ask you for your blender path and do some other magic in the background (writing some config files)

**Comment by Tianesus** [comment]
Ah yup! That seems to have done it, doing a wipe of the plugin again on Blender, Clearing GoZ cache files, then setting everything up again afterwards seems to have done it. 

Thank you very much for all of the troubleshooting!

**Comment by kromar** [comment]
great to hear that this worked:D let me know if you run into any other issues.

**Comment by Tianesus** [comment]
Hey, returning with a related issue, I've reinstalled my OS so I had to set up my programs again and once more I'm having trouble exporting from Blender to Zbrush.

To start off, there are two separate issues depending on an option:

If I have "Clean Project Files" ticked, the export just fails and seems to for some reason look for an older exported file.
![image](https://user-images.githubusercontent.com/5891260/150658055-85579855-f278-4bfc-ae19-5bec97aed2dd.png)
![image](https://user-images.githubusercontent.com/5891260/150658053-0ca3d1d4-b0c7-47fa-ad48-1db08d6d7d85.png)

If I have "Clean Project Files" unticked, hitting export and causing zbrush to open up gives the familiar error I posted about in the OP. It seems that also every time zbrush is freshly opened, it forgets the assigned Blender directory, and I have to re-assign it.

![image](https://user-images.githubusercontent.com/5891260/150658072-127fd378-f540-48c2-aea6-ea269e100749.png)
![mage](https://user-images.githubusercontent.com/5891260/139598206-65b7828a-54ee-4569-9ba9-929e9c40d56c.png)
![image](https://user-images.githubusercontent.com/5891260/150658159-a88ff7af-3423-47b5-9526-d640736b37ca.png)

 At that point, after assigning the Blender directory, exporting from Blender to Zbrush seems to first spit out the star subtool, followed by the cube. It does that reliably, one after another.
![image](https://user-images.githubusercontent.com/5891260/150658274-6048090c-4b7f-411e-8f1d-780839ecddca.png)

Exporting from zbrush to Blender seems to work out fine right now, but the Blender > Zbrush workflow is currently entirely not possible.

I've tried the GoZ for Zbrush installer from within the Blender plugin, I've tried clearing the GoZ cache files, I've also tried reinstalling the Blender plugin entirely, so far it's not been working out, but I'm willing to try again.

My Zbrush version is 2022.0.2, Blender is 3.0.0, and plugin is taken from the Master (3.5.66).
