### ISSUE TITLE
import button text is not translated to other languages than English

### ISSUE THREAD

**Issue by kair1234** [JoseConseco/GoB#274]
![image](https://user-images.githubusercontent.com/1472884/147394147-06d52825-3c4b-4037-ad9e-5e22cb7566f1.png)

**Comment by kromar** [comment]
not sure i understand this question? is this about the translation of some parts of the addon? if so can you provide some screenshots?

**Comment by kromar** [comment]
this is fixed in master v3.5.67
https://github.com/JoseConseco/GoB
