### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by alxk2p** [JoseConseco/GoB#275]
![GoB_error](https://user-images.githubusercontent.com/64592888/141956294-3cd2411b-121e-4387-aa9f-b3f4628c0b2f.jpg)
Hi there!
GoB addon for Blender doesn't export. Tried in Blender 2.82 and 2.92. How can I fix it? Import works well.

**Comment by alxk2p** [comment]
I'm  using Windows 10.

**Comment by schroef** [comment]
Are you admin of that that user? The exporter doesnt have writing permission it seems

**Comment by kromar** [comment]
can you try the latest version and see if you still get the issue? https://github.com/JoseConseco/GoB/releases/tag/v3_5_66

**Comment by alxk2p** [comment]
The same issue with the latest version, unfortunately. And yes, it's admin user.

**Comment by kromar** [comment]
can you try this:
run the GoZ installer
![Screen Shot 11-06-21 at 01 05 PM](https://user-images.githubusercontent.com/1472884/143690083-36e1ee5f-7d6f-46ba-ad44-27917abb9aaa.PNG)

then close blender and open zbrush and clear the cache, then restart zbrush and GoZ a tool from zbrush, this should ask you for your blender path and do some other magic in the background (writing some config files)

![Screen Shot 11-06-21 at 01 06 PM](https://user-images.githubusercontent.com/1472884/143690092-f13f0966-3b13-42a5-a388-d7eb7bd0087d.PNG)
![Screen Shot 11-06-21 at 01 06 PM 001](https://user-images.githubusercontent.com/1472884/143690124-b3b592e0-435e-4469-bfc9-7e162b2e4e02.PNG)

now try to send a mesh again from blender to zbrush

**Comment by alxk2p** [comment]
It works now! Thanks a lot!!!
