### ISSUE TITLE
When zbrush subtool has scale factor send to blender and return to zbrush the scale factor will change to 1 

### ISSUE THREAD

**Issue by 879096600** [JoseConseco/GoB#276]
When zbrush subtool has scale factor send to blender and return to zbrush the scale factor will change to 1 ,so other subtools become 2mm size . I’m tried many new versions gob ,it’s all have same problems. just Version 3.41 gob it’s ok.  When blender file Go to zbrush the Scale factor  Won’t change to 1  .hope fix it , thank you very much!

**Comment by kromar** [comment]
hm version 3.41 is a loong time ago and a lot of things have changed, but i assume if it was working at some point it should be possible to fix this. 
Im not exactly sure what you mean with scale factor? is it the subtool size?
![image](https://user-images.githubusercontent.com/1472884/142516483-6536a516-f779-4a3d-8f1f-68b7afd7e150.png)

**Comment by kromar** [comment]
i think i see what you are referring to, are you changing the export scale?
![image](https://user-images.githubusercontent.com/1472884/142517183-463cf2eb-f963-4cbb-86c4-8508f4933d67.png)

**Comment by 879096600** [comment]
![](https://user-images.githubusercontent.com/1472884/142517183-463cf2eb-f963-4cbb-86c4-8508f4933d67.png)   
yes it is, some lager units model will automatic conversion scale factor to match zbrush edit it ,so send to blender and return to zbrush the scale factor will change to 1  ,only version 3.41 do not change it .I am upgrad new version gob many times  ,and reback to 3.41.

**Comment by 879096600** [comment]
![Snipaste_2021-11-19_18-36-59](https://user-images.githubusercontent.com/69351419/142609066-de9b7722-25d6-4c51-97d1-efad42c35f07.jpg)

**Comment by 879096600** [comment]
Especially large models will not work properly when moving brushes inside zbrush, consult zbrush official said 2mm is the best sculpting size, that's why there is a scale option, so that models larger than 2mm will be converted to the maximum 2mm, so that the sculpting can work properly.

**Comment by kromar** [comment]
can you try this version and see if this solves your issue?

v3.5.67
https://github.com/kromar/blender_GoB/archive/refs/heads/prevent-export-scale-change.zip

**Comment by 879096600** [comment]
I just tried it and the new version solved the problem, thank you very much! Because this problem has been bothering me for a long time. I can jump directly from version 3.41 to the latest version now
