### ISSUE TITLE
Blender problems after GoB install

### ISSUE THREAD

**Issue by Corusso** [JoseConseco/GoB#278]
My blender gob install now using zbrush 2022 update has caused blender not to start up. Is there any solution to this.  After removing gob from add-ons blender works fine but cannot export to zb any more. Thank you.

**Comment by Corusso** [comment]
Tried to direct ti bush 2021 but gives same result. Blender will not boot if this Add-on is installed.

**Comment by kromar** [comment]
what do you mean with blender not starting up? i dont think blender ever started when sending something from zbrush, at least i know that there are things missing for this so it would surprise me if that worked for you:O

Do you get any errors when trying to send to zbrush?
Also please tell me which GoB version you are using and which blender version so i can try to reproduce this issue.

**Comment by Corusso** [comment]
Blender works fine and the GoB works fine on initial try, but after that blender will not boot if i quit the program and try to re-start. I only go from blender to Zbrush have not done the reverse. My work-around has been to disable the GoB add-on after I use it because if i keep it on, the next time i try to run blender it will not start up. no error message at all. I am on an iMac pro running Monterey and Zbrush 2022, blender 2.93.6. I tried an earlier version of GoB and had the same result.

**Comment by Corusso** [comment]
And thank you!

**Comment by kromar** [comment]
how do you disable the addon once you cant start blender any more? i can not think of a reason why this could happen, i will need to jump to my mac and see if i can reproduce that issue.

**Comment by Corusso** [comment]
in the add on preferences I just unblock the box. if i forget to do that i need to go to users>application support and delete all the GoB files and re install the add-on.
<img width="836" alt="Screen Shot 2021-11-27 at 8 57 27 AM" src="https://user-images.githubusercontent.com/95004670/143690272-801b51ab-caa8-4d1b-9cb9-313eb4d1f45a.png">

**Comment by kromar** [comment]
hm ok that is very strange. i will try to reproduce this

**Comment by kromar** [comment]
i can not reproduce this. do you have any other addons enabled? if so can you try disable those and leave GoB enabled and see if you still encounter this?
There is nothing in Gob that should prevents blender from starting.

**Comment by Corusso** [comment]
Thank you so much!!! I disabled all the import/export extensions i did not absolutely need and now it is working as expected. Phew!

**Comment by kromar** [comment]
if you know which addon was causing the conflict would be very useful. maybe you can find out which one causes it so i can find out what the conflict is.

**Comment by Corusso** [comment]
Well i turned on each Add-on one at a time and GoB was still working so no telling .....
Thanks again for your help.

**Comment by kromar** [comment]
oh well maybe we find out one day, thanks for tryig to find the source.
Glad it works:D
