### ISSUE TITLE
More Blender to Zbrush export issues

### ISSUE THREAD

**Issue by Tianesus** [JoseConseco/GoB#283]
Hey, returning with an issue related to the one I've had troubleshooting with in the past. I've reinstalled my OS so I had to set up my programs again and once more I'm having trouble exporting from Blender to Zbrush.

To start off, there are two separate issues depending on an option:

If I have "Clean Project Files" ticked, the export just fails and seems to for some reason look for an older exported file.
![image](https://user-images.githubusercontent.com/5891260/150658055-85579855-f278-4bfc-ae19-5bec97aed2dd.png)
![image](https://user-images.githubusercontent.com/5891260/150658053-0ca3d1d4-b0c7-47fa-ad48-1db08d6d7d85.png)

If I have "Clean Project Files" unticked, hitting export and causing zbrush to open up gives the familiar error I posted about beforehand. It seems that also every time zbrush is freshly opened, it forgets the assigned Blender directory, and I have to re-assign it.

![image](https://user-images.githubusercontent.com/5891260/150658072-127fd378-f540-48c2-aea6-ea269e100749.png)
![mage](https://user-images.githubusercontent.com/5891260/139598206-65b7828a-54ee-4569-9ba9-929e9c40d56c.png)
![image](https://user-images.githubusercontent.com/5891260/150658159-a88ff7af-3423-47b5-9526-d640736b37ca.png)

 At that point, after assigning the Blender directory, exporting from Blender to Zbrush seems to first spit out the star subtool, followed by the cube. It does that reliably, one after another.
![image](https://user-images.githubusercontent.com/5891260/150658274-6048090c-4b7f-411e-8f1d-780839ecddca.png)

Exporting from zbrush to Blender seems to work out fine right now, but the Blender > Zbrush workflow is currently entirely not possible.

I've tried the GoZ for Zbrush installer from within the Blender plugin, I've tried clearing the GoZ cache files, I've also tried reinstalling the Blender plugin entirely, so far it's not been working out, but I'm willing to try again. 

My Zbrush version is 2022.0.2, Blender is 3.0.0, and plugin is taken from the Master (3.5.66).

**Comment by kromar** [comment]
thanks for reporting the issues, i will see if i can preproduce them so i can provide a solution for it.
