### ISSUE TITLE
GoB can import, but not export after updating to B3 - GoB3.5.66

### ISSUE THREAD

**Issue by VincentDN** [JoseConseco/GoB#291]
![Gob Bug](https://user-images.githubusercontent.com/67105078/163010611-55d80061-deeb-49df-b224-68314eca533e.jpg)
Hey everyone,

Thanks for this great plugin! I am struggiling to get GoB to work in the newest blender 3.1. After installing, importing will work fine but exporting will throw up this error. Can anyone help?

**Comment by kromar** [comment]
thanks for reporting the issue, it seems there was a wrong input that so far has not shown. i made a fix which is available in the latest master tag: v3_5_68 or you can download the zip here: https://github.com/JoseConseco/GoB/archive/refs/heads/master.zip
Would be great if you let me know if it solves your issue.

**Comment by VincentDN** [comment]
Hey Kromar,

Working perfectly! Do note that the GoB defaults to looking for Zbrush 4R8 path, you may want it to look for the latest Zbrush by default. Thanks for this wonderful plugin, I couldnt use Blender without it. If there's ever any way I can help, let me know

V

**Comment by kromar** [comment]
great to hear and thanks for the feedback, im happy to hear that you enjoy the addon! 
ah yes that is something i wanted to do at some point, i will put it on the todo list and come back to it later.
