### ISSUE TITLE
Errors with modifiers when exporting

### ISSUE THREAD

**Issue by curlygcradlerock** [JoseConseco/GoB#296]
I'm having trouble getting the modifiers applied when exporting meshes from blender to zbrush.  Under GoB export options, I have chosen "Export and Apply" for the modifiers.  But upon exporting I get the following error:
![image](https://user-images.githubusercontent.com/104387922/165155742-a0e33a65-7b82-43a4-b2b4-dc6b8c7ed17a.png)

**Comment by kromar** [comment]
Hi, it looks like you are not using the latest GoB version, can you try it with this one and see if you still have the issue? 
https://github.com/JoseConseco/GoB/archive/refs/tags/v3_5_69.zip

**Comment by curlygcradlerock** [comment]
Awe man, I updated GoB today, but somehow not to the most recent - my apologies!

After updating modifier exports work as expected and everything is awesome once again.  Thank you!

**Comment by kromar** [comment]
Im happy to hear that it solved your issue. Thanks for making the effort to report it.

**Comment by curlygcradlerock** [comment]
Thanks again for the help!

Just a quick thought I figured I'd share - For whatever reason when I search for the GoB tool publicly, it seems to only show 3_5_66

google
![GoB_01](https://user-images.githubusercontent.com/104387922/165310519-aac6edad-8cc5-4bdf-83c6-82e5e5e68913.jpg)


Github
![GoB_02](https://user-images.githubusercontent.com/104387922/165310554-ea564f68-afea-4b5e-b01c-90bd4603c02a.jpg)

Github List
![GoB_03](https://user-images.githubusercontent.com/104387922/165310619-bc18bfc7-0e7a-4958-aa8d-8b8bbbedce3b.jpg)

**Comment by kromar** [comment]
yes im aware of that, i made some changes to the scaling which i dont want to push into a release yet since i want to do some more testing on that.

**Comment by curlygcradlerock** [comment]
10-4  Thanks again
