### ISSUE TITLE
Export from Zbrush wrong smooth normals calculated

### ISSUE THREAD

**Issue by koloved** [JoseConseco/GoB#30]
but when i enter to Edit Mode the issue is gone

see: https://youtu.be/oXwj0LE7c48

**Comment by kromar** [comment]
@koloved can you provide some details what you did to end up with the wrong normals on the cube?

**Comment by koloved** [comment]
@kromar nothing, just import model from Zbrush, objects has wrong shading, before enter to edit mode

**Comment by kromar** [comment]
@koloved im able to reproduce the issue, thanks for reporting it, i will see if i can find out why this happens.

**Comment by kromar** [comment]
@koloved i fixed the problem and also added a option so you can choose if the meshes should be flat or smooth shaded when they arrive in blender.
https://github.com/JoseConseco/GoB/pull/32

if you want to give it a try you can use this verison:  https://github.com/kromar/blender_GoB/tree/bugfix/fix_shading

**Comment by koloved** [comment]
Oh yes , its working,  thank you! youre great !
