### ISSUE TITLE
i cant install gob in blender

### ISSUE THREAD

**Issue by ColorHaoo** [JoseConseco/GoB#308]
<img width="750" alt="WX20220513-025113@2x" src="https://user-images.githubusercontent.com/105455801/168147680-5780a2ef-2bfa-4b9a-8520-1621acd815f9.png">
system
macos :12.3
blender:3.1.2

i cant install gob

**Comment by kromar** [comment]
thanks for reporting the issue, can you try version 3.5.73 and see if it resolves your issue.
https://github.com/kromar/blender_GoB/tree/fix-macos-public-path
https://github.com/kromar/blender_GoB/archive/refs/heads/fix-macos-public-path.zip

**Comment by ColorHaoo** [comment]
ok,i try v3.5.73,and it was installed successfully
but i had installed v3.5.66 successfully before in blender 3.1
thants again!
