### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by MatthewRead42** [JoseConseco/GoB#317]
Hi I keep getting an AttributeError Exporting from Blended to Zbrush I don know why

Python: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.2/scripts/addons/materials_utils/menus.py", line 121, in draw
    icon_value = material.preview.icon_id
AttributeError: 'NoneType' object has no attribute 'icon_id'
![AttributeError](https://user-images.githubusercontent.com/18283473/173201812-e88d1eac-cdbf-4eb1-a227-1b10e99a6301.png)

**Comment by kromar** [comment]
Hi, please try the latest version 3.5.73, you seem to be on a quite old version and many things have been fixed/improved sicne then,
you can download it here:
https://github.com/JoseConseco/GoB/archive/refs/heads/master.zip
https://github.com/JoseConseco/GoB

**Comment by MatthewRead42** [comment]
Hi Kromar,
Thank for that.
Matt

**Comment by kromar** [comment]
glad it worked! have fun
