### ISSUE TITLE
This is the problem when it is transferred from the blender to the zbrush.

### ISSUE THREAD

**Issue by moai0924** [JoseConseco/GoB#319]
There is a workflow that I want to do now.

Cad ▶ Sketchup ▶ Blender, ZBrush ▶ Lumion I want to continue the work flow.

So I hope it's a situation where it's moved from the sketchup in the middle to the blender or the Zbrush, and it's imported and exported from the blender and the zbrush. 

The modeling below is a situation that was brought from sketchup to blender. I think it came very well. However, as soon as it was imported with a Zbrush, the modeling was immediately damaged and moved to a Zbrush. What kind of action is required? Is it impossible?

It's the process from top to bottom. 
The second picture is the current polygon situation.

![1](https://user-images.githubusercontent.com/107386300/173485533-8f41ce6e-261b-4600-8f98-f3e070529a90.png)

![2](https://user-images.githubusercontent.com/107386300/173485548-386bf519-ee12-4f80-a17a-f5651d118e02.png)

![3](https://user-images.githubusercontent.com/107386300/173485553-913e6ce4-8080-46c9-ac3d-7bdf3b1ff080.png)

![4](https://user-images.githubusercontent.com/107386300/173485567-3cadd9d2-a36a-4527-a9f7-009229d8b39c.png)

**Comment by kromar** [comment]
hmm not sure what is ogoing on, is it popssible you share a part of such a file so i can take a closer look at this?

**Comment by moai0924** [comment]
Two files, Sketchup and Blender. The uploaded blender file is the uploaded sketchup file opened as 'skp importer'.
I sent it to you via email.

**Comment by kromar** [comment]
i did not get any mail, maybe you sent it to Jose instead of me?

**Comment by moai0924** [comment]
The e-mail 
notifications@github.com
No? I sent it again.

**Comment by kromar** [comment]
that is not my mail, looks like some github support mail

**Comment by moai0924** [comment]
[ruin.zip](https://github.com/JoseConseco/GoB/files/8962617/ruin.zip)

I am sending you the file again. Can you download it now?

**Comment by kromar** [comment]
yes that works, it looks like you have a lot of non manifolds which can cause some issues. There is a option to disable the deletion of these mesh elements which you probably want to keep.
Disabling this should fix your issue.

![image](https://user-images.githubusercontent.com/1472884/175228859-7503a828-a989-4067-aae4-23806a95ac6e.png)
