### ISSUE TITLE
Mirror X axis for GOB

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#325]
### Discussed in https://github.com/JoseConseco/GoB/discussions/321

<div type='discussions-op-text'>

When I select "Flip up axis" and "Flip forward axis", the model is incorrectly mirrored in the X axis in Blender. Is there any way to have a "Mirror X axis" check box so the two apps will match in orientation?

</div>

**Comment by loresuto** [comment]
Hello, I've attached an image showing the settings I'm using in GOB and the mirroring issue I see in Blender. You can see that the R and L written on the model are reversed in Blender.
Thanks
![GOB_mirroredXaxis](https://user-images.githubusercontent.com/76023122/175180288-ad5ddc8e-37c6-4e3f-91ad-cdcbb67d1c9a.jpg)

**Comment by kromar** [comment]
uh yeah that does not look right, thanks for reporting i will have a look at this.

**Comment by kromar** [comment]
i need to ask what you expect, mirroring will introduce some flipping so im not sure what you are exactly doing. Can you describe the exact steps you are performing and what you expect to be different?

**Comment by loresuto** [comment]
Sorry, I'm not used to Github and I didn't see this comment.

What I want to happen is for the model imported from Zbrush to be rotated 180 degrees in Blender, so that it's facing forward to match the orientation in Zbrush, but NOT mirrored.

My goal is to have the Zbrush orientation and the Blender orientation match, without flipping/mirroring the model. Instead, the model should be rotated to match the Zbrush orientation.

Hope that makes sense!

Thanks

**Comment by kromar** [comment]
this should be fixed in version v3_5_89, would be great if you could give it a try and see if it behaves as you expect.
https://github.com/kromar/blender_GoB/tree/fix-mirror-issues

**Comment by loresuto** [comment]
Hello, I just tried this build several times... Unfortunately, this hangs Blender every time I try to import. Windows 10, Blender 3.2.1.

Thanks

**Comment by kromar** [comment]
thanks for testing, this hanging might be related to some performance issues with polygroup import due to some new additions. Can you try to disable the4 polygroup import or with lower resolution model?
![image](https://user-images.githubusercontent.com/1472884/179839123-186873b4-9ac5-454d-92bf-a613cb92bfee.png)

of course this would just be to confirm that the mirror issues are fixed and i can focus on fixing those performance issues.

**Comment by loresuto** [comment]
I did the test with a low poly model, which imported correctly, with correct orientation and no flipping!

**Comment by kromar** [comment]
@loresuto  i merged a first performance improvement, mainly for the slow polygroups so maybe you want to use that if you need polygroups.

version 3_5_90
https://github.com/JoseConseco/GoB/archive/refs/heads/master.zip

**Comment by loresuto** [comment]
Great, I installed it. I usually turn polygroups off. It's usually just the polypaint info I use. Do you use Zbrush much?
