### ISSUE TITLE
Could you please check if polygroup export works, because for some reason polygroups just wont export. On ver v3_5_86. I'm exporting them per face map option, but switching to vertex group doesn't fix the issue. It's importing the polygroups as face maps but nothing or completely wrong faces are selected. (I Restarted both applications)

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#353]
Could you please check if polygroup export works, because for some reason polygroups just wont export. On ver v3_5_86. I'm exporting them per face map option, but switching to vertex group doesn't fix the issue. It's importing the polygroups as face maps but nothing or completely wrong faces are selected. (I Restarted both applications)
![image](https://user-images.githubusercontent.com/85735034/181063435-af7da1b3-1bdd-475a-95b1-62ab9714b237.png)

_Originally posted by @Epicrex in https://github.com/JoseConseco/GoB/discussions/335#discussioncomment-3233075_

**Comment by kromar** [comment]
Thanks for reporting this issue, i am able to reproduce some issues from zbrush to blender but not the other way around. Is that what you also encounter? I have a bit a hard time to understand in which direction you are sending the mesh/polygroup.

**Comment by Epicrex** [comment]
Yes just like you say, from ZBrush to blender. I rarely do the polygroups in blender, the tools in ZBrush are just much better for that

**Comment by kromar** [comment]
the issue should be fixed with version 3_5_91, i will create a new release when you can confirm that this fixes your issue as well.

https://github.com/JoseConseco/GoB/archive/refs/tags/v3_5_91.zip

**Comment by Epicrex** [comment]
Great, I'll try it out later today

**Comment by Epicrex** [comment]
Polygroups work on ver 3_5_91 again as usual👍

**Comment by kromar** [comment]
great thanks for reporting and testing! I will make a new release with this fix.
