### ISSUE TITLE
Bad quality after import to Blender

### ISSUE THREAD

**Issue by artyombon** [JoseConseco/GoB#355]
Hello!
When importing to Blender after sculpting in Zbrush the quality is worse.
Fisrt image is Zbrush, second is Blender.
![2022-07-28_10-31-42](https://user-images.githubusercontent.com/72221191/181448535-2737af1b-fd47-4afc-8f98-e3721ea427ae.jpg)
![2022-07-28_10-32-03](https://user-images.githubusercontent.com/72221191/181448561-b21f4a7e-04d2-4b0f-9526-d66d52b2b59e.jpg)

**Comment by kromar** [comment]
do you have any subdivision on the model in zbrush? GoZ only exports the lowest subdivision so if you want to get the highres over you will need to apply it or create a copy with the applied subdivisions.
