### ISSUE TITLE
Not able to select faces in vertex group coming back from zbrush

### ISSUE THREAD

**Issue by ghettobob** [JoseConseco/GoB#369]
I have the option to use polygroups for vertex groups in the import from GoB and the groups show up from the import but I when I click on the vertex group and choose select it hightlights nothing like the group is now empty.

**Comment by kromar** [comment]
Hi, can you provide some more information what blender version, zbrush version and addon version you are using and if possible a zbrush file from which the import fails?

**Comment by ghettobob** [comment]
I was using latest version of the plugin, 3.5.92 and am using the subscription service for Zbrush so I think it's currently 2022.0.5. Blender is version 3.3.0
When I send them over to zbrush and it appropriately assigns the polygroups based on the vertex groups... but when it comes back from zbrush into blender the polygroups to vertex groups doesn't work, they show no data assigned to any of the vertex groups.

**Comment by kromar** [comment]
@ghettobob did you enable the option to import vertex groups from poly groups? This option is by default disabled and could explain why the import from zbrush to blender is not working for you 
![image](https://user-images.githubusercontent.com/1472884/198627756-a6ee6e1b-814b-442d-bae0-45b8a0f1df05.png)
