### ISSUE TITLE
Export button greyed out for objects that have no modifiers?

### ISSUE THREAD

**Issue by naitadev** [JoseConseco/GoB#371]
When I create any object the Export button is greyed out. Adding any modifier to it enables the button. This doesn't feel normal, but is it? Using Maxon ZBrush 2022.0.6 / Blender 3.3.1 and 3.2.0 in Windows 64bit
![gobissue](https://user-images.githubusercontent.com/69494947/194988301-487aa2cd-65b9-4018-8add-64a253abf1ea.png)

**Comment by kromar** [comment]
Thanks for reporting this issue, it is indeed not normal. I hope you can work around this issue until i get to it, im super busy right now.

**Comment by naitadev** [comment]
Thanks for the quick reply. A simple workaround is to add a subdivision modifier set to no divisions, that does the trick for me for the time being

**Comment by Mellma** [comment]
저기, 여유가 있다면 이 방법을 사용해봐!
https://github.com/JoseConseco/GoB/issues/372#issuecomment-1285798649

**Comment by naitadev** [comment]
> Look, if you can afford it, use this method! [#372 (comment)](https://github.com/JoseConseco/GoB/issues/372#issuecomment-1285798649)

That worked great, thank you!

**Comment by kromar** [comment]
I got a fix for this but since it turns out there are many scenarios to be covered it would be great if you could use it for a bit and see if there is anything unexpected happening.

https://github.com/kromar/blender_GoB/tree/fix-export-poll
