### ISSUE TITLE
Can't export from Blender

### ISSUE THREAD

**Issue by vilmasa** [JoseConseco/GoB#372]
It was a fiddly installation for MacOs but finally got the link between ZBrush and Blender to work. The only problem is that even though I can export from ZBrush to Blender with no problems I can't seem to do the same from Blender. The button to export is completely greyed out and it doesn't let me do anything with it. I assumed the problem was that I hadn't selected the object but no matter how I use object or edit mode it doesn't make a difference. Sorry for the Finnish, but should there be a script for exporting too in the Blender folder? I'm using 3.3.1 Blender and 2022.0.5 ZBrush. I also cannot troubleshoot inside Blender, as the icon just shows a question mark and nothing is clickable! Thanks!

<img width="940" alt="Näyttökuva 2022-10-15 kello 20 52 51" src="https://user-images.githubusercontent.com/115898733/196005351-84710927-2de8-4ef5-a616-b3363fd338e0.png">

<img width="1680" alt="Näyttökuva 2022-10-15 kello 20 51 53" src="https://user-images.githubusercontent.com/115898733/196005321-3da8d67a-aac4-4cb2-b03f-36eca277a817.png">

<img width="965" alt="Näyttökuva 2022-10-15 kello 20 57 22" src="https://user-images.githubusercontent.com/115898733/196005478-71091f0b-f1fd-4b7d-8b5a-f4d7b977be81.png">

**Comment by vilmasa** [comment]
Just noticed that someone else had the same problem and it was indeed a bug! Adding a modifier solves the issue for me too.

**Comment by Mellma** [comment]
I've experienced a similar problem with the blender "3.3LTS".

I don't know your blender version, but if you use the "3.3LTS version", you can solve it in that way.

1. Open the file "GoB.py" from the path below (use "VSCode" or "Notepad")
> Path: C:\Users\chern\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\GoB-3_5_93

2. Press "Ctrl+F" and enter "export_poll" to find the part that starts with "def export_poll(cls, context)." (See example screenshot)
![image](https://user-images.githubusercontent.com/84716250/196998489-120335c2-e411-4cb0-916d-4fbbca2430e4.png)


3. Check the sentence "if len(context.selected_objects) <= 1"

4. Correct "<=1" to "<" (see red "#!" in the example screenshot)
![KakaoTalk_20221020_175001514](https://user-images.githubusercontent.com/84716250/196998605-9b36d40b-d98f-4a32-a63b-2cf8f7225da2.png)

**Comment by kromar** [comment]
I got a fix for this but since it turns out there are many scenarios to be covered it would be great if you could use it for a bit and see if there is anything unexpected happening.

https://github.com/kromar/blender_GoB/tree/fix-export-poll
