### ISSUE TITLE
Export button is unavailable

### ISSUE THREAD

**Issue by WizardGroon** [JoseConseco/GoB#373]
![resim_2022-10-22_162612867](https://user-images.githubusercontent.com/48471118/197341558-471d4dcc-1cbf-4c87-814c-b04987e3881b.png)

Export path is right i am hundred percent sure. I can import from zbrush but cant export to zbrush.

**Comment by REKKU68** [comment]
Hey Look, Hey, try this way.
https://github.com/JoseConseco/GoB/issues/372#issuecomment-1285798649

**Comment by MetinSeven** [comment]
This seems to be a bug that in the latest version, 3.5.93, causing the Export button to remain ghosted if only one object is selected in Blender. As soon as you select multiple objects, export to ZBrush works. At least here it does.

For reference: exporting one object still works in version 3.5.56

**Comment by REKKU68** [comment]
> This seems to be a bug in the latest version, 3.5.93, causing the Export button to remain ghosted if only one object is selected in Blender. As soon as you select multiple objects, export to ZBrush works. At least here it does.
> 
> For reference: exporting one object still works in version 3.5.56, maybe in other releases prior to 3.5.93 as well.

Aha! I guess the reason is not the blender version, but the latest version of the add-on?
If so, it seems highly likely that the developer accidentally modified the code.
Thank you.

**Comment by kromar** [comment]
I got a fix for this but since it turns out there are many scenarios to be covered it would be great if you could use it for a bit and see if there is anything unexpected happening.

https://github.com/kromar/blender_GoB/tree/fix-export-poll

**Comment by MetinSeven** [comment]
> I got a fix for this but since it turns out there are many scenarios to be covered it would be great if you could use it for a bit and see if there is anything unexpected happening.
> 
> https://github.com/kromar/blender_GoB/tree/fix-export-poll

Tried it, and it seems to work fine so far, thanks! 👍
