### ISSUE TITLE
Export from Blender 3.0 to ZBrush 2022 doesn't work

### ISSUE THREAD

**Issue by Jursit** [JoseConseco/GoB#374]
Hey, I've just installed the plugin for Blender v. 3.0,
in my case it works only for import from ZB to Blender, but in Blender Export button is not active.
I tried to re-install it but result is the same.
Probably I will try with another version of Blender.
![image](https://user-images.githubusercontent.com/47368674/197397453-200ab967-cf1b-4d0e-a6be-e8a6b5c39042.png)

**Comment by Jursit** [comment]
Finally fixed this issue using this solution: 
https://github.com/JoseConseco/GoB/issues/372#issuecomment-1285798649

**Comment by kromar** [comment]
I got a fix for this but since it turns out there are many scenarios to be covered it would be great if you could use it for a bit and see if there is anything unexpected happening.

https://github.com/kromar/blender_GoB/tree/fix-export-poll
