### ISSUE TITLE
Can't export any mesh from Blender 3.2.0 to Zbrush 2022

### ISSUE THREAD

**Issue by pointh0** [JoseConseco/GoB#375]

**Comment by MetinSeven** [comment]
Multiple issues have already been opened for this. [Try selecting more than one object in Blender.](https://github.com/JoseConseco/GoB/issues/373#issuecomment-1289510457)

**Comment by pointh0** [comment]
Yeah, I figured  that it was weird tha you needed two objects and that's why i was asking why i can't export only one, If it's a bug that's okay, thanks.
