### ISSUE TITLE
Can't export in blender 3.3

### ISSUE THREAD

**Issue by seid111** [JoseConseco/GoB#382]
So i move from blender 3.1 to 3.3.1 then i clean install everything follow the txt, but i can't export blender to zbrush (zbrush to blender is normal)
what can i do now? 
![image](https://user-images.githubusercontent.com/117804852/204178635-b5f91b42-984a-4c33-8cbf-bb7ecc24e82c.png)

**Comment by seid111** [comment]
> what is your addon version?

I install GoB_v3_5_95

**Comment by frankjonen** [comment]
Same here, just downloaded and installed. Shows up in ZBrush and Blender but the buttons in Blender only trigger errors.

**Comment by kromar** [comment]
My guess here is that its because you have the addon on the admin account of windows which requires special administrator rights to run. You might need to run blender with Administrator rights to make this work or consider using a normal user account.

**Comment by kromar** [comment]
what is strange that it seemed to work with blender 3.1, can you try to run the GoZ repair and see if that fixes the issue? maybe a target folder is not existing and then windows reports a elevation error instead of a missing folder structure or some strange thing like that.
