### ISSUE TITLE
Neither Blender nor Zbrush send all objects to each other except for the selected one

### ISSUE THREAD

**Issue by lifelover90** [JoseConseco/GoB#385]
My ZB version is 2022.0.5 and Blender 3.2.2. I've been trying to send over models from Zbrush to Blender and back, however only the selected subtool gets sent and if modified gets updates across both programs respectively. All subtools that I want to transfer are visible and the object names are different yet something prevents to make it happen. 

I also checked the the log and here's a snapshot of it:

"C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GoB-3_5_92/Blender/ C:\Users\Public\Pixologic/GoZApps/Blender/
Windows Popen:  C:\Program Files\Pixologic\ZBrush 2022\ZBrush.exe
C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GoB-3_5_92/Blender/ C:\Users\Public\Pixologic/GoZApps/Blender/
Windows Popen:  C:\Program Files\Pixologic\ZBrush 2022\ZBrush.exe
C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GoB-3_5_92/Blender/ C:\Users\Public\Pixologic/GoZApps/Blender/
Windows Popen:  C:\Program Files\Pixologic\ZBrush 2022\ZBrush.exe
C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GoB-3_5_92/Blender/ C:\Users\Public\Pixologic/GoZApps/Blender/
Windows Popen:  C:\Program Files\Pixologic\ZBrush 2022\ZBrush.exe
C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GoB-3_5_92/Blender/ C:\Users\Public\Pixologic/GoZApps/Blender/
Windows Popen:  C:\Program Files\Pixologic\ZBrush 2022\ZBrush.exe
C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GoB-3_5_92/Blender/ C:\Users\Public\Pixologic/GoZApps/Blender/
Windows Popen:  C:\Program Files\Pixologic\ZBrush 2022\ZBrush.exe
C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GoB-3_5_92/Blender/ C:\Users\Public\Pixologic/GoZApps/Blender/
Windows Popen:  C:\Program Files\Pixologic\ZBrush 2022\ZBrush.exe"

Any idea what happens?

**Comment by kromar** [comment]
thanks for reporting the issue, can you try the latest version and see if this fixes your issue? https://github.com/JoseConseco/GoB/releases

**Comment by lifelover90** [comment]
@kromar thanks for the reply! I realized that to transfer all the objects from Zbrush I had to press "All" or "Visible" instead of "GoZ". My ignorance. Anyway, is there a way to do so from Blender, though, instead transfering only a single/active object?

**Comment by kromar** [comment]
at the moment only the selected get exported, but this could be a additional feature. The question would be how to add it, there is currently a double assignment on the export button (normal mouse click = export as subtool, ctrl/shift + mouse button = export as tool) and that could easily be extended to maybe use alt+mouse button to send all. However this is a bit hidden. I would like to avoid having a additional button if possible.

**Comment by lifelover90** [comment]
@kromar I understand your point. By the way, is there any option to prevent GoZ from dropping the subtool to the lowest subdivision upon transfering without deleting them first?

**Comment by kromar** [comment]
Unfortunately there is not, that is a design that pixologic implemented and i can not modify unless i would add a custom exporter.

**Comment by lifelover90** [comment]
Alright. Thank you for your response and hard work in maintaining this addon. It saves a ton of time. :)

**Comment by kromar** [comment]
you are welcome and thanks you for reporting issues, it helps making the addon better and easier to maintain!
