### ISSUE TITLE
Cannot Install GoB Blender 2.91

### ISSUE THREAD

**Issue by jonweb98** [JoseConseco/GoB#393]
Getting the following error when trying to use GoB. Tried changing directory name from "GoB-master" to just "GoB" but did not work.
![GoB Error](https://user-images.githubusercontent.com/79741947/208328644-2f9b0664-af4d-4f12-a808-ca2c23a7768d.JPG)

**Comment by kromar** [comment]
Hi, thanks for reporting the issue. I recently introduced some code which apparently is not working with older python/blender versions. This should be fixed in this release:
https://github.com/JoseConseco/GoB/releases/tag/V3_5_98
