### ISSUE TITLE
Most of Mesh Disappears when Exporting from Blender

### ISSUE THREAD

**Issue by LordNed** [JoseConseco/GoB#399]
Blender Version: 3.4
GoB Addon Version: 3.5.98
ZBrush Version: 2022.0.6

I've been back and forth between Blender/ZBrush a lot, but this is the gist of what I know about this particular mesh:
1) I worked on it in ZBrush and Blender
2) I exported it from Blender
3) I added polygroups and edge creases in ZBrush
4) I used ZModeler to extrude along some of the created polygroups
5) I GoB'd it out of ZBrush (wanted to check if I polygroups/creases would get preserved or not)
6) It imports with extrusions into Blender. I immediately export back from Blender.
7) Most of the mesh disappears. One part of the ZModeler work I did stays, the rest disappears.

Before Export:
![IMG_20230119_blender_23-16-32](https://user-images.githubusercontent.com/955414/213638838-6e2e621e-ede5-4c84-b408-ff60c0e2d84f.png)

I press Export in GoB:
![IMG_20230119_23-16-56](https://user-images.githubusercontent.com/955414/213638889-2e82c246-2da7-465c-b55e-fed3f7bae564.png)

The mesh in Blender changes to just part of it, the rest disappears. The model that shows up in ZBrush matches what is now visible in Blender.

If I Ctrl Z, and delete the highlighted edgeloop:
![IMG_20230119_23-17-30](https://user-images.githubusercontent.com/955414/213638989-fc40ac85-a456-463e-bd5b-1f49d37efe5b.png)

Then that half of the mesh stays, the mirrored half that I didn't delete the edgeloop from disappears:
![IMG_20230119_blender_23-18-36](https://user-images.githubusercontent.com/955414/213639152-85190ade-6087-4999-ac47-9528e56becbb.png)

If I delete other verticies (such as on the toes), it doesn't "fix" the export and it disappears as per the original issue, so something about touching those faces specifically (which was the edgeloop I extruded with ZModeler) seems to help.

Attached is the Blender file (zipped since Github doesn't like .blend). Since the issue seems to be on the Blender file I didn't try with a new ZBrush file, and the polygon I'm deleting is what I actually wanted to delete anyways so the problem is worked around, but this is totally bizarre. 

[gob_disappearing_shoes.zip](https://github.com/JoseConseco/GoB/files/10464048/gob_disappearing_shoes.zip)

**Comment by kromar** [comment]
Thanks for reporting the issue, this is a known one and is related to the export option 'Delete internal faces'. If you disable it your mesh should be fine.
