### ISSUE TITLE
Error encountered while importing file

### ISSUE THREAD

**Issue by KsuZhar** [JoseConseco/GoB#403]
![01](https://user-images.githubusercontent.com/124359898/216593518-a67010d2-3d9e-4570-a207-f6cae5479a45.JPG)
![Безымянный](https://user-images.githubusercontent.com/124359898/216593525-7e5f6e15-847e-49ab-9044-281c9dbc86c0.jpg)
![03](https://user-images.githubusercontent.com/124359898/216593533-9ded5e6e-7ff4-47b0-a387-e2fcfb99d577.jpg)

An error occurred when I exporting the model from the blender. I see my model in the list of tools in zbrush, but it is displayed as some strange thing

**Comment by kromar** [comment]
Could you share a file where this happens or know the exact steps to reproduce this? its hard to reproduce with a file that causes it.
