### ISSUE TITLE
Export from zbrush to blender is not working 

### ISSUE THREAD

**Issue by danjaworsky** [JoseConseco/GoB#406]
There is already an issue here for this, but I'm having the same problem. Export from blender to zbrush works just fine, but when clicking the GOZ button in Zbrush I get : 

Unable To Open File
!:/users/Shared/Pixologic/GoZBrush/Scripts/GoZ_ExportFromZBrush

**Comment by kromar** [comment]
Thanks for reporting this issue and for posting a solution! 
For future reference, the GoZ installer can also be run from within the Troubleshoot section of the GoB addon
![image](https://user-images.githubusercontent.com/1472884/236928269-246b91ef-727d-44ea-aacc-e8de2aedc930.png)
