### ISSUE TITLE
3.0.6 doesn't seem to respect collections

### ISSUE THREAD

**Issue by 3Rton** [JoseConseco/GoB#41]
By default when you create an object it is assigned to the last selected collection. However, Gob seems to always import new objects to the top level. It'd be nice if it respected selected/last selected collection.

**Comment by kromar** [comment]
that is a good point, thanks for reporting it. i guess this should not be to hard to do.

**Comment by kromar** [comment]
@3Rton can you give this a try? https://github.com/kromar/blender_GoB/tree/feature/add_to_collection
it should add the object to the selected /active collection if the object is not already in blender, if the object is already in a collection it will be reassigned to the new active collection.

**Comment by 3Rton** [comment]
> @3Rton can you give this a try? https://github.com/kromar/blender_GoB/tree/feature/add_to_collection
> it should add the object to the selected /active collection if the object is not already in blender, if the object is already in a collection it will be reassigned to the new active collection.

Works! 
Design wise I might personally only assign to collection when the object is not already in the scene. After you move in zbrush from creating subtools to mostly working on the existing subtools youll probably keep sending to Blender often to preview. At this point it might become a pain to have to always make sure you have the right collection selected before sending from Zbrush. (especially if you have a complicated file with multiple collections where you might be going between collections for lights, backgrounds etc between sends) 

That being said this is already nice improvement as is so thumbs up.

**Comment by kromar** [comment]
That is a good point, i did this because it was adding it to the new selected collection and the you wpuld eventually end up with the object in all selections. 
So you would rather have it just in the initial collection where it was imported?

**Comment by kromar** [comment]
@3Rton i changed it so it should behave like you proposed. would be great if you could try it and let me know if everything works as expected now.

**Comment by 3Rton** [comment]
It's exactly as I wanted. I used it for about 3 hour session and didn't notice anything broken. (Albeit it was past midnight so I might have missed stuff) Seems to work great.

**Comment by kromar** [comment]
@3Rton glad it works as expected now:D 
I fix a bug that i encountered and simplified the code, would be great if you could test the latest version and let me know if you run into any issues.
https://github.com/kromar/blender_GoB/tree/feature/add_to_collection
