### ISSUE TITLE
export a curve with modifiers in blender to zbrush, swap and keep modifiers

### ISSUE THREAD

**Issue by SbstnDC** [JoseConseco/GoB#413]
Hello GOB people.

yesterday we tried with some friends to export a geometry that has modifiers, we send to goz with gob, and edit in zbrush, when we return to blender the piece, we see that it has transformed it to geometry and no longer has the modifiers, in the case of correlative pieces with the suffix name ".001", in zbrush they appear renommbradas as "_001"

![image](https://user-images.githubusercontent.com/22725270/236330908-7edfc965-8159-4adb-ba5b-b4d6c9cad743.png)

![image](https://user-images.githubusercontent.com/22725270/236331061-b9b76a90-3d9d-44c5-8589-252454fe3c60.png)

Greetings

**Comment by kromar** [comment]
Thanks for reporting this issue, can you make sure you have the Modifier Export set to "Export Only" and not "Apply and Export". 
![image](https://user-images.githubusercontent.com/1472884/236933013-bdb3ee3f-99e7-4a70-807d-2d961b4174a5.png)
