### ISSUE TITLE
Vertex Paint from Blender to Zbrush on 3.5+ not working 

### ISSUE THREAD

**Issue by AckeemD** [JoseConseco/GoB#414]
Previously Vertex paints worked both ways but on 3.5+ it hasn't been, not only does it not transfer but it removes it from zbrush when meshes are exported so a fix for this would be great, Thanks.

**Comment by kromar** [comment]
i made a fix for the vertex colors, would be great if you could see if it works for you

v3.6.0
https://github.com/kromar/blender_GoB/tree/fix-vertex-colors
https://github.com/kromar/blender_GoB/archive/refs/heads/fix-vertex-colors.zip
