### ISSUE TITLE
Gob doesn't send the entire model to zbrush. Any idea why?

### ISSUE THREAD

**Issue by NowaPerspektywa098** [JoseConseco/GoB#416]
Model before pressing export button:
![image](https://github.com/JoseConseco/GoB/assets/101328465/dcfda9be-eecb-465b-b1ed-b3b1d82cee85)
![image](https://github.com/JoseConseco/GoB/assets/101328465/0e1957fe-7ca7-47f9-89d9-9f460b554c86)
![image](https://github.com/JoseConseco/GoB/assets/101328465/f4c5e9c8-08c2-4247-b1be-9487184b518d)
Model after pressing export button:
![image](https://github.com/JoseConseco/GoB/assets/101328465/ef0b6de9-57da-4ef9-a014-137c549aecdc)
![image](https://github.com/JoseConseco/GoB/assets/101328465/8f71ea2c-428d-4b5f-94db-6f70567e5ab2)
![image](https://github.com/JoseConseco/GoB/assets/101328465/f303ccad-1e09-43ad-bd65-a78f53b92f86)

I tried flipping normals, applying modifiers, removing bevel weight and crease but no matter what I did the result was the same. Any advice?

**Comment by kromar** [comment]
hi, this might be related to the export option "Delete Internal Faces" which might delete some faces in your scenario
![image](https://github.com/JoseConseco/GoB/assets/1472884/789a6384-a744-4393-b58a-8c10a2c2ef49)

**Comment by NowaPerspektywa098** [comment]
Hello. I've already solved the problem. I have changed the color of the normals in blender so that I can see right away that the normals are rotated. Unfortunately, I didn't enable this option (to see normal colors) and after a long time I figured it out. Anyway, thank you for your help.
