### ISSUE TITLE
Not exporting polypaint frome Zbrush to blender

### ISSUE THREAD

**Issue by badoubadou** [JoseConseco/GoB#422]
Hi, 
Thanks for the plugins, it's great !
I just tested it, and I have a problem.
When I paint in Zbrush, UV unwrap, the create texture from polypaint, normal maps & displacement, and send it to Blender, the model only have the polypaint, not the textures, normal and displacement.
Any idea why ?
Sorry I found out you need to create a texture, and then it works. 
Thanks

**Comment by badoubadou** [comment]
My bad, it works, sorry

**Comment by kromar** [comment]
Hi, thanks for reporting the issue, i made some fixes for the vertex color/polypaint transfer with blender 3.5+ let me know if you encounter some more issues with this as i couldn't fully reproduce your issue.
https://github.com/kromar/blender_GoB/tree/fix-vertex-colors
https://github.com/kromar/blender_GoB/archive/refs/heads/fix-vertex-colors.zip
