### ISSUE TITLE
find a way to work with face sets in blender 4.0

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#425]

**Comment by Alexm38** [comment]
Face map removal is definitely an issue. Maybe it is possible to use vertex paint or materials instead?

**Comment by afeso** [comment]
Hi, regarding this, I found an addon that can convert face sets into vertex groups and using GOB, I could export those vertex grop as polygroups. 

I've run a simple test, and this worked fine. The main issue now though, is how to get those polygroup into blender as face sets, as now sending back to blender only comes in as vertex groups. 

here's the addon: https://blenderartists.org/t/uv-maps-attributes-vertex-groups-from-face-sets/1471291

![image](https://github.com/JoseConseco/GoB/assets/17725011/977ecf23-0bf3-4205-92fd-bf2b2b3df069)

![image](https://github.com/JoseConseco/GoB/assets/17725011/4e2be9d3-24a1-42d7-8b3b-828d8732abd1)

**Comment by GeneralLuminescent** [comment]
Not sure if this is known here or not but apparently you can create face sets via Node Tools specific nodes for face sets. I made a blend file of this example, nothing complicated. [https://www.dropbox.com/scl/fi/3qeoouhlkbyc83qcsv1md/Face-Set-Nodes.blend?rlkey=iamjc0rzj4outh8g5v2oyacci&dl=0](url)

I did export a FBX from Zbrush with Polygroups as Materials option enabled and I was able to load in the polygroups from Zbrush as Face Sets in Blender with the node tool in the blend file I linked. I didn't know how to load it in as a non-material attribute to be honest. 

However, if Blender can retrieve the polygroups as an attribute from the GOZ file perhaps this method or similar might help with this issue? It just seems to me this is the Blender devs solution to replacing Face Maps altogether.

**Comment by kromar** [comment]
Thanks to @00004707 Face sets are available in this branch in version 4.1.5: https://github.com/kromar/blender_GoB/tree/extensions-platform-review
