### ISSUE TITLE
Error:  when I click the check box to Add the Add-On. 

### ISSUE THREAD

**Issue by Liferocka** [JoseConseco/GoB#426]
Hi I installed the update to my Blender 4.0 in the preferences, Add, check box, I get an error. it will not turn on the Add-On. 
![Screen Shot 2023-08-26 at 4 51 45 PM](https://github.com/JoseConseco/GoB/assets/50764172/5fdf4f13-57c3-4297-925f-9bf5f527c46d)

**Comment by kromar** [comment]
fixes for blender 4.0 can be found here: https://github.com/JoseConseco/GoB/issues/418
