### ISSUE TITLE
Vertex Color/Polypaint Round Trip Issues (with v3_6_0)

### ISSUE THREAD

**Issue by LordNed** [JoseConseco/GoB#427]
I saw there were some other Issues touching on the same topic but the users hadn't tried the update.

Before 3.6.0 I could paint in zBrush, GoB it to Blender, and I would get vertex colors on meshes, but I could not round-trip - sending it back to zBrush resulted in a white painted mesh in zBrush.

After installing 3.6.0, Materials are not automatically being created in Blender which makes it appear that importing vertex colors does not work.

Repro:
Set the following GoB settings:
![image](https://github.com/JoseConseco/GoB/assets/955414/f039c1e1-d1d0-4d44-9021-4570bd9cb1f8)
![image](https://github.com/JoseConseco/GoB/assets/955414/0a95a071-33e3-459d-8d9e-a6af7a71d76f)

In ZBrush, insert a PolyMesh3D star to your sub-tool list. Go to "Color" and then "Fill Object" (after choosing a non-white color)
GoZ it to Blender.
In Blender, switch the Viewport to Material Preview. Click your PolyMesh3D star.
Check that it has a "Col" Color Attributes group, but **no material is assigned.**
![image](https://github.com/JoseConseco/GoB/assets/955414/24b37703-f763-4e38-b7ce-26f3534bbaf7)

Make a mesh edit (such as changing a vertex location), and Export it back to zBrush. Note that the colors correctly round-tripped (even if you couldn't see them in Blender).
![image](https://github.com/JoseConseco/GoB/assets/955414/ee07a775-4149-4309-98c4-e8afb872e97a)

If you make a material and assign the Color Input, then you can see vertex colors.
![image](https://github.com/JoseConseco/GoB/assets/955414/200bc2af-2c28-4a5b-9829-3edb9c753a9a)

Side note: I had some confusion after upgrading, existing meshes that I had been working with were only partially round-tripping (which is why I've edited this Issue 3 times now 😄). When I started with a new mesh in zBrush and imported it into a new object in Blender, that exposed only the Material issue, the actual vertex colors correctly round-trip regardless of the material. So users may run into confusion if they upgrade and then try using it on a project that was already WIP.

Blender 3.6.2
GoB: 3.6.0
zBrush: 2022.0.6

**Comment by kromar** [comment]
Thanks for reporting, this looks like the material creation is not working any longer for vertex colors.
Just to verify that i understand correctly, the confusion comes from the missing material which should be created from importing with the "Import material from polypaint" option?

**Comment by kromar** [comment]
I made a fix for this issue in v3.6.1 let me know if you run into some other issues
https://github.com/kromar/blender_GoB/archive/refs/heads/fix-import-material-from-polypaint.zip

**Comment by LordNed** [comment]
@kromar That version fixes the issue, and I can successfully round-trip from zBrush -> Blender -> zBrush, thank you!

**Comment by kromar** [comment]
@LordNed version 3.6.1 has the latest fixes, it is not yet back in master since there have been other issues discovered with polypaint so im looking into that. This is the issue where it is mentioned: https://github.com/JoseConseco/GoB/issues/412
