### ISSUE TITLE
Ability to change scale for import/export

### ISSUE THREAD

**Issue by Video-Nomad** [JoseConseco/GoB#43]
When exporting characters (~160-200 cm height) to Maya, Max, Marmoset or UE4 it is optimal to set scale to 100 in ZBrush (Tool->Export->Scale). 

With this scale you have adequate size of objects in ZBrush units (compared to default Unified Box) and FBX exporter and GoZ work correctly for other programs.

However for GoB 100 scale means x100 during export and Blender shows incorrect scales (for 200cm object it shows 20000cm).

It is very inconvenient to change ZBrush scale from 100 to 1 and back every time I want to work with GoB and Blender.

There was a similar issue with Marvelous Designer GoZ plugin and they just added two parameters for import and export scale so you can dial everything manually.

Is there a way to add this to GoB? Like a separate option in Add-ons/GoB?

Here are some images for reference. Every program is set to use cm and GoZ was used:
ZBrush:
![ZBrush](https://user-images.githubusercontent.com/37882690/63945978-01b6f100-ca7d-11e9-913d-d37d59032e0c.png)
Maya:
![Maya](https://user-images.githubusercontent.com/37882690/63946005-0d0a1c80-ca7d-11e9-8e2f-b64d037f3aa0.png)
Max;
![Max](https://user-images.githubusercontent.com/37882690/63946009-0f6c7680-ca7d-11e9-86bf-6d2bf19f8534.png)
Marmoset:
![Marmoset](https://user-images.githubusercontent.com/37882690/63946012-109da380-ca7d-11e9-9ec9-c50d8f9197eb.png)
Blender:
![Blender](https://user-images.githubusercontent.com/37882690/63946014-11ced080-ca7d-11e9-9088-e696214fd8c1.png)

**Comment by kromar** [comment]
@Video-Nomad thanks for reporting this, i think this should be easy to add.

**Comment by Video-Nomad** [comment]
Yea, this works. It exports to and from Blender correctly now. FBX export and import works as well. However, you need to change clip start and clip end for the default viewport camera (they got messed up after scale change) and maybe other values as well. I'm not sure how 0.01 Unit Scale will behave with other Blender tools like simulation and modifiers. Should theoretically work.
![5QeiVImYeq](https://user-images.githubusercontent.com/37882690/64045576-55573680-cb72-11e9-9151-6583bf5901ab.png)
![gdsB41xZlJ](https://user-images.githubusercontent.com/37882690/64045577-55573680-cb72-11e9-9d46-3454658ff7d4.png)

**Comment by kromar** [comment]
great! i have been using unit scale at work for about 10 years and have not come across issues with it.
