### ISSUE TITLE
Blender 4.0.0 Beta Export Error to ZBrush 2023

### ISSUE THREAD

**Issue by Ruteger** [JoseConseco/GoB#432]
![image](https://github.com/JoseConseco/GoB/assets/146396959/ba8d693a-8b12-4bd8-942a-f1042c90eff9)

**Comment by kromar** [comment]
Hi @Ruteger thanks for reporting this issue, have you tried the version for blender 4? 
https://github.com/kromar/blender_GoB/tree/update-for-blender-4

**Comment by Ruteger** [comment]
It works! Thank you...
________________________________
