### ISSUE TITLE
Import from Zbrush works but export from Blender doesn't

### ISSUE THREAD

**Issue by Galoras** [JoseConseco/GoB#434]
I'm getting this error when exporting from Blender to Zbrush, importing from Zbrush to Blender using GoZ works though.

![image](https://github.com/JoseConseco/GoB/assets/93441195/64f2e22e-095c-421c-8ee2-23d65acb5559)

**Comment by kromar** [comment]
You should update your blender or use a older version of GoB.
Im not supporting older blender versions with the latest versions.

**Comment by Galoras** [comment]
Thought it'll be something like that, thanks, working perfectly on 3.6.
