### ISSUE TITLE
Please, help with a problem

### ISSUE THREAD

**Issue by Ivan121q** [JoseConseco/GoB#436]
![Screenshot_358](https://github.com/JoseConseco/GoB/assets/61443831/de9b98ec-73dd-43e4-afdf-c6bbbecbf53d)

**Comment by Ivan121q** [comment]
The problem was solved

made a small change

# --Polypaint--
if obj.data.color_attributes.active_color_index:                
    vcoldata = me.color_attributes[obj.data.color_attributes.active_color_index].data 

# --Polypaint--
if obj.data.color_attributes and obj.data.color_attributes.active_color_index >= 0:
    vcoldata = me.color_attributes[obj.data.color_attributes.active_color_index].data

**Comment by kromar** [comment]
thanks for reporting and proposing the fix, i added it to the blender 4 fixes branch.
