### ISSUE TITLE
There is an error like that i don't understand

### ISSUE THREAD

**Issue by SAYFAXX** [JoseConseco/GoB#437]
Python: Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\GoB-master\GoB.py", line 1372, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\GoB-master\GoB.py", line 1286, in execute
    self.exportGoZ(PATH_GOZ, context.scene, obj, f'{PATH_PROJECT}')
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\GoB-master\GoB.py", line 895, in exportGoZ
    if obj.data.color_attributes.active_color_name:                
AttributeError: 'Mesh' object has no attribute 'color_attributes'

location: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py:132

location: <unknown location>:-1

**Comment by kromar** [comment]
Hi @SAYFAXX, it looks like you are using blender 3.0 which is not supported by the new versions of the addon. Please consider updating to blender 3.6 or using a older version of the GoB addon.

**Comment by 4lexez** [comment]
Hi @SAYFAXX, I also had this problem, it was tedious to find the solution, but i finally made it! 
Try to follow this instructions:
https://www.yamato-tsukasa.com/gob-install-manual-3-5-52/
I know this is in jananese language, but with translate I manage to solve the problem.
I used blender 3.0.0, Zbrush 2022.0.6 and GoB addon provided in the link.
Also if blender addon gives you a permission denied error, just check the boxes to allow full access for creator owner.
@kromar Message for you: I don't know why, but in your new script the part of the code starting from # --Polypaint-- is not working anymore, but in older version of addon (which is in the link) it is working just fine, so i give you a tip that maybe you should roll back that code part or try to find the solution in this field.
But I'm not a very good programmer and may not understand the full depth of the problem, but I don't see anything wrong with offering a solution that I noticed works fine for me. 
Also, if you also found this helpful, I would love it if you could tell others how to fix this error or create a hotfix.
![NewCode](https://github.com/JoseConseco/GoB/assets/66371974/aab8be1f-68ba-4913-86c8-0f70495ad90c)
![OldCode](https://github.com/JoseConseco/GoB/assets/66371974/307d57ce-0f94-447b-a315-99dd90a62798)

**Comment by kromar** [comment]
@4lexez thanks for providing a solution, it seems that many users on on older versions of blender which i did not anticipate. I think the proper way to fix this is to use the app.version detection and have the addon work for both blender versions.

`if bpy.app.version < (3,5,0): 
    # run code for older blender versions
else:
    # run code for newer blender versions
`
i will see if i get around to make a patch for this but its hard for me to find a moment to work on this. The blender 4 version however will be tricky to support this way as there will be more code and its harder to support many different blender version over time.

**Comment by 4lexez** [comment]
@kromar Man, I totally understand you, it's hard to support something unofficial like this addon, but anyway good luck with it.
Maybe right now you can make a hint in txt file or in this site idk for new users to choose the right version of addon when downloading it, because for me personally when i firstly downloaded this addon it was clear in my mind that the newest version will provide a functional in every version of blender. Even in youtube videos this is shown as something intuitive.
But anyway, thank you for your hard work

**Comment by kromar** [comment]
https://github.com/JoseConseco/GoB/releases/tag/v3_6_2
I added a fix in the latest release for this issue. Let me know if you encounter any other errors.
