### ISSUE TITLE
Object has no attribute 'active_color_name' (Blender 3.2)

### ISSUE THREAD

**Issue by Angrinreal** [JoseConseco/GoB#438]
Hi, I have this issue when exporting my mesh to Zbrush. I also tried to add a material and vertex colors to the mesh, but it didn`t help.

```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\GoB\GoB.py", line 1373, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\GoB\GoB.py", line 1287, in execute
    self.exportGoZ(PATH_GOZ, context.scene, obj, f'{PATH_PROJECT}')
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\GoB\GoB.py", line 896, in exportGoZ
    if obj.data.color_attributes.active_color_name:                
AttributeError: 'bpy_prop_collection' object has no attribute 'active_color_name'. Did you mean: 'active_color_index'?
Location: C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py:115
```

**Comment by kromar** [comment]
Hi @Angrinreal, the later version do not support old ble der versions. You should either update blender to version 3.6 or use a older version of the GoB addon.

**Comment by 4lexez** [comment]
Hi @Angrinreal, I also had this problem, it was tedious to find the solution, but i finally made it!
Try to follow this instructions:
https://www.yamato-tsukasa.com/gob-install-manual-3-5-52/
I know this is in jananese language, but with translate I manage to solve the problem.
I used blender 3.0.0, Zbrush 2022.0.6 and GoB addon provided in the link.
Also if blender addon gives you a permission denied error, just check the boxes to allow full access for creator owner.

**Comment by kromar** [comment]
https://github.com/JoseConseco/GoB/releases/tag/v3_6_2
I added a fix in the latest release for this issue. Let me know if you encounter any other errors.
