### ISSUE TITLE
Import Button No Longer Working

### ISSUE THREAD

**Issue by joebuehrer** [JoseConseco/GoB#44]
The Import button is no longer working. I click on it, and it doesn't change color to signify it's active. Furthermore, I can no longer import/export models between Zbrush and Blender. This happened after my version of windows installed updates and after I uninstalled previous versions of Zbrush off my machine.

**Comment by kromar** [comment]
@joebuehrer can you try to run the GoZ repair insude the Zbrush support folder and see if that fixes the issue?

can you  check blenders system console and post any errors you get there?
![image](https://user-images.githubusercontent.com/1472884/64040782-128b6380-cb5e-11e9-8935-2fbd53ecc1e5.png)

**Comment by joebuehrer** [comment]
I figured it out. I had uninstalled previous versions of Zbrush tok make space on my drive and that's what caused the issue. Once I reinstalled 2019.1 the issue was fixed.
