### ISSUE TITLE
Addon can not be activated, Python error

### ISSUE THREAD

**Issue by LordOfDragons** [JoseConseco/GoB#443]
```
GoB Unkonwn System:  Linux
TypeError: StringProperty() argument 5 must be str, not bool
Exception in module register(): /home/roland/.config/blender/3.6/scripts/addons/GoB/__init__.py
Traceback (most recent call last):
  File "/opt/progs/blender-3.6.0-linux-x64/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/home/roland/.config/blender/3.6/scripts/addons/GoB/__init__.py", line 59, in register
    [bpy.utils.register_class(c) for c in classes]
  File "/home/roland/.config/blender/3.6/scripts/addons/GoB/__init__.py", line 59, in <listcomp>
    [bpy.utils.register_class(c) for c in classes]
ValueError: bpy_struct "GoB_Preferences" registration error: 'pixologoc_path' StringProperty could not register (see previous error)
```

Install from Zip file after renaming according to Readme file

**Comment by kromar** [comment]
Hi @LordOfDragons , linux is currently not supported and since i am not using that system i would need to know some more details to support it.
Is there a tutorial on how to rum zbrush on linux so i could try to set it up myself or could you explain how you do that?

**Comment by JoseConseco** [comment]
@LordOfDragons how did u made zbrush run on linux?

**Comment by LordOfDragons** [comment]
ZBrush is not running on Linux, and I'm not using ZBrush, I'm a Blender user. What I wanted is trying to get some free VDM based brushes into Blender to see if and how well this works.

**Comment by kromar** [comment]
Ok, so i assume the VDM brushes come as ztl files?

**Comment by LordOfDragons** [comment]
No, it comes as ZBP file.
