### ISSUE TITLE
Blender 4.0 Beta imports Zbrush 2023.2.2 error

### ISSUE THREAD

**Issue by siciyuanweilai** [JoseConseco/GoB#447]
This script is used:
https://github.com/JoseConseco/GoB/releases/tag/v4_0_1

Wrong question:
![QQ截图20231104172736](https://github.com/JoseConseco/GoB/assets/52228169/726ef41a-4f00-42fd-9589-03517a117ce0)

Blender 4.0 Beta:
![QQ截图20231104172716](https://github.com/JoseConseco/GoB/assets/52228169/f2626c1b-371b-403b-b555-6a68a4eb1bd7)

**Comment by atticus-lv** [comment]
have the same problem

**Comment by OakenPixel** [comment]
Give the mesh a color attribute, this solves the problem for me
![Screenshot 2023-11-09 104847](https://github.com/JoseConseco/GoB/assets/118230786/652dc477-dc97-4b98-8a3c-df54fe4466a2)

**Comment by siciyuanweilai** [comment]
> Give the mesh a color attribute, this solves the problem for me ![Screenshot 2023-11-09 104847](https://user-images.githubusercontent.com/118230786/281688926-652dc477-dc97-4b98-8a3c-df54fe4466a2.png)

This worked and temporarily solved the problem, thank you.

**Comment by atticus-lv** [comment]
ok, just fix it in code and open a pull request #448
now it works

https://github.com/JoseConseco/GoB/assets/64118610/29f107f8-02f1-4880-8df4-c47d8e1ec885

**Comment by kromar** [comment]
Thanks for reporting the issue. This issue should be fixed in this pre release. Let me know if there are issues with it.
https://github.com/JoseConseco/GoB/releases/tag/v4_0_2
