### ISSUE TITLE
Nothing is happening when pressing the export button

### ISSUE THREAD

**Issue by sonny6405** [JoseConseco/GoB#45]
Hello,
I just downloaded GOB for Blender 2.8 but nothing is happening when I press the export button...

I followed the instructions and the path is made in zbrush. 
I don't know what to do :(

**Comment by kromar** [comment]
@sonny6405  did you get it to work?

**Comment by sonny6405** [comment]
> @sonny6405 did you get it to work?

I don't know how but I did... haha

**Comment by kromar** [comment]
sometimes it needs the softwares to be started again or some strange thing like that:D im glad you got it working!
