### ISSUE TITLE
Export does not seem to work in 4.0

### ISSUE THREAD

**Issue by KungFuCactus** [JoseConseco/GoB#452]
Tried using the export option in 4.0 for the first time and got the following error:

![image](https://github.com/JoseConseco/GoB/assets/151736821/ec38716f-f28b-4507-9768-b192c97a8428)

Using the latest version of addon (3_6_3), and the previous version; both have the same error. Using the both versions of the addons works fine in 3.6 still.

**Comment by SerujiShard** [comment]
![image](https://github.com/JoseConseco/GoB/assets/85259237/99b0d3fb-ad87-4fd4-ae34-7413392b034f)

Similar error here

**Comment by kromar** [comment]
Please use the latest release 4.0.2 https://github.com/JoseConseco/GoB/releases/tag/v4_0_2

**Comment by KungFuCactus** [comment]
@kromar Thanks, that fixed it. I didn't find this version because I hit the update button on the addon itself in preferences, and this actually located v3_6_3, not the latest release 4.0.2. 4.0.2 is also not shown as the latest version in the main page of the repo, it's still v3_6_3.  In order to find 4.0.2, I had to check the "Experimental Versions" checkbox under the addon preferences.

![image](https://github.com/JoseConseco/GoB/assets/151736821/42cf3016-ace3-43c5-9f53-a5152c486d6c)

Anyway, thanks again. This addon is a huge help in the workflow.

**Comment by SbstnDC** [comment]
same here

Python: Traceback (most recent call last):
  File "C:\Users\sebas_pe87e9k\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-3_6_3\GoB.py", line 1448, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\sebas_pe87e9k\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-3_6_3\GoB.py", line 1360, in execute
    remove_internal_faces(obj)
  File "C:\Users\sebas_pe87e9k\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-3_6_3\GoB.py", line 2026, in remove_internal_faces
    bpy.ops.object.mode_set(bpy.context.copy(), mode='EDIT')
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109

**Comment by kromar** [comment]
> @kromar Thanks, that fixed it. I didn't find this version because I hit the update button on the addon itself in preferences, and this actually located v3_6_3, not the latest release 4.0.2. 4.0.2 is also not shown as the latest version in the main page of the repo, it's still v3_6_3. In order to find 4.0.2, I had to check the "Experimental Versions" checkbox under the addon preferences.
> 
> ![image](https://private-user-images.githubusercontent.com/151736821/285214577-42cf3016-ace3-43c5-9f53-a5152c486d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzYyNTMsIm5iZiI6MTcwNDI3NTk1MywicGF0aCI6Ii8xNTE3MzY4MjEvMjg1MjE0NTc3LTQyY2YzMDE2LWFjZTMtNDNjNS05ZjUzLWE1MTUyYzQ4NmQ2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwOTU5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODIyYWZlOTFlMjE4M2E5Nzg0ZGVhYjgxYTBmY2M2YmI5MTQ4NTcxMzgxYWJjMzc4NTNlMGQzZmUxYzc3Zjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qrxqrfn1K5d4vj9PbxUCRgWItFsi9lld4sNlsh3kYXs)
> 
> Anyway, thanks again. This addon is a huge help in the workflow.

thanks for sharing the issue with the updater. I only released the version as a pre release at the point where you run into the error which caused the update not to show properly on your side. Its nice to see that the updater is used.
