### ISSUE TITLE
A bug regarding exporting masks from ZBrush to Blender.

### ISSUE THREAD

**Issue by jshengst** [JoseConseco/GoB#453]
Exporting masks from Blender to ZBrush works fine (I manually assign vertex weights to the mask vertex group), but when exporting masks from ZBrush to Blender, the result is incorrect: regardless of whether there is a mask in ZBrush or not, the exported mask vertex group in Blender contains all vertices of the mesh.

I am using ZBrush 2024 and Blender 3.6.3.

Thank you for your plugs，and it is helpful for me.

**Comment by kromar** [comment]
hi @jshengst  what version of GoB are you using? 
Have you tried the latest version of GoB? https://github.com/JoseConseco/GoB/releases/tag/v4_0_2

**Comment by jshengst** [comment]
The issue of losing masks when exporting from ZBrush to Blender (some masks becoming full masks) is something I encountered while using Blender 3.6.7, ZBrush 2024, and GoB-3_6_3.

When retesting with the new version, GoB-4_0_2 (Blender 3.6.7, ZBrush 2024, and GoB-4_0_2), I encountered another problem: not only do the old version ZBrush masks still have issues exporting to Blender, but I also cannot properly export ZBrush polygroups to Blender vertex groups.

Due to the new version GoB-4_0_2 removing the functionality of exporting from face maps to ZBrush polygroups, I had to use the option of exporting from Blender vertex groups to ZBrush polygroups in the settings. I am unsure if this is caused by my incorrect settings, but I request that you restore the functionality of exporting polygroups from face maps as the vertex group method cannot accurately describe the surface information of the polygroups.
(I do not know what the ZScripts folder is for in the plugin directory, so I have not touched it.)

**Comment by kromar** [comment]
Ok, i was not aware that there was/is a issue with masks. 
Im aware of the lack of face sets, unfortunately they have been completely removed and only face attributes can be used which dont have any interface for the user outside of geonodes as far as im aware. 
I have not had the time to look into all of that but as far as i know it should be possible to pass the polygroups on to the face maps which are used in blenders sculpt mode which was the initial idea anyways but there has not been a way in blender to do that properly.

**Comment by kromar** [comment]
@jshengst  ![image](https://github.com/JoseConseco/GoB/assets/1472884/d66470ad-bebc-4d04-ad3f-96e41581b10a)
The masking seems to work fine for me with vertex groups.
Can you be more specific and/or provide a example / exact steps so i can reproduce what you encounter?

**Comment by jshengst** [comment]
The main problem occurs during the export process from ZBrush to Blender. Exporting models, masks, and polygon groups from Blender works fine, but there is a certain probability of encountering an error during this process (see image). When using GoZ in ZBrush, Blender will automatically update the model under normal circumstances, but when the model cannot be updated automatically (which happens frequently), clicking the Manual button to update it manually will inevitably result in this error. At the same time, in version 4.0.2, Blender cannot receive the polygon group exported from ZBrush normally: exporting masks will create a blank vertex group in Blender, and nothing will happen when exporting polygon groups.
<img width="1280" alt="Snipaste_2024-01-06_22-10-22" src="https://github.com/JoseConseco/GoB/assets/30409747/e0ec3145-d08c-4628-b0f4-071dc8814210">

I tested for several hours but could not determine the cause of the error, which is really frustrating. Since all the problems occur during the export process from ZBrush to Blender, I suspect that the error is caused by my GoB plugin installation. How should the "ZScripts/GoB_Import.zsc" file in the plugin directory be used?

Since I have been using Blender 3.6, I only discovered that the face mapping function was removed in Blender 4.0, which made the export of polygon groups very tricky. All attempts above were made in Blender 3.6.2, ZBrush 2024.1.17, and GoB 4.0.2. Next, I may not be in the mood to try the export process from ZBrush to Blender again. However, GoB still greatly optimizes my workflow, thank you.

**Comment by kromar** [comment]
> How should the "ZScripts/GoB_Import.zsc" file in the plugin directory be used?
This script handles how the data is imported in zbrush when it comes from blender. Since the error happens when importing in blender it is not caused by this script. I also dont think its due to the installation but some corner case. Its really hard to fix something if it can not be reproduces and so far i can not reproduce the error.

**Comment by kromar** [comment]
There is a new release which should fix some of your issue https://github.com/JoseConseco/GoB/releases/tag/v4_0_3
