### ISSUE TITLE
not working in blender 4.0.0

### ISSUE THREAD

**Issue by ITXGANESH** [JoseConseco/GoB#454]
it shows some error when i am trying to export through blender

**Comment by Limbicnation** [comment]
Identical problem encountered in Blender 4.0.2.

**Comment by SbstnDC** [comment]
![image](https://github.com/JoseConseco/GoB/assets/22725270/3f5d091a-3d19-4e21-b6ef-210c43be764d)

**Comment by kromar** [comment]
please use the latest release: https://github.com/JoseConseco/GoB/releases/tag/v4_0_2
