### ISSUE TITLE
It stop working 

### ISSUE THREAD

**Issue by kinoomich** [JoseConseco/GoB#455]
![Screenshot_333](https://github.com/JoseConseco/GoB/assets/48155428/cf622cbf-ad75-4d42-9a82-2afb1437aba3)

**Comment by kromar** [comment]
please use the latest version of GoB https://github.com/JoseConseco/GoB/releases/tag/v4_0_2

**Comment by kinoomich** [comment]
Thank yoU!

ср, 3 янв. 2024 г. в 16:34, Daniel G ***@***.***>:
