### ISSUE TITLE
issue when exporting from blender to zbrush

### ISSUE THREAD

**Issue by Cyphpython** [JoseConseco/GoB#457]
![BugBlenderToZbrush](https://github.com/JoseConseco/GoB/assets/90405810/14e82bf3-9898-4852-86c2-8e29eeac6829)

**Comment by buzzkirill** [comment]
Make sure you've updated to the latest version. I had a similar error but an update fixed it

**Comment by kromar** [comment]
There is a new release which should fix your issue https://github.com/JoseConseco/GoB/releases/tag/v4_0_3
