### ISSUE TITLE
Gob only export 1/2 of mesh to zbrush.

### ISSUE THREAD

**Issue by ashdalat** [JoseConseco/GoB#460]
I am having trouble with an addon. I imported a quad mesh from Marvelous as an OBJ file into Blender and packed the UV. My intention was to paint the texture in ZBrush, so I used GoB to export it. However, when I clicked on 'export', half of the mesh disappeared. I am using Blender version 4.0.2. I then tried exporting the mesh as OBJ and importing it into ZBrush, which worked fine. But when I exported the mesh back into Blender, the same issue reappeared. here is the blender file https://drive.google.com/file/d/1Ks4JxfwlHftkjSpy8Gv08PDpzWLGbxK9/view?usp=drive_link , the file got the bug is the cloth one

**Comment by kromar** [comment]
![image](https://github.com/JoseConseco/GoB/assets/1472884/d59c1161-514f-446e-993b-c136b8dc52b5)
Hi, you will need to disable this option in the export settings "Delete internal faces"
