### ISSUE TITLE
Bug(?) Report (Some strange change on ZBrush

### ISSUE THREAD

**Issue by Nourkias** [JoseConseco/GoB#464]
If i click "GoZ/ALL" when using Transpose(Brush
It will change Transpose to "Draw"
and when i switch it back to Transpose
the "Focal Shift -100" is changed to "Focal Shift 0"
Which is quite annoying
![Step1](https://github.com/JoseConseco/GoB/assets/161498012/be5a3202-2967-4869-8264-28ed1390d8f3)
![Step2](https://github.com/JoseConseco/GoB/assets/161498012/6e06cd91-edba-4da3-808c-a9dbc33262aa)
![Step3](https://github.com/JoseConseco/GoB/assets/161498012/1ffa12b6-6cc0-401a-a189-9072858b9942)

**Comment by kromar** [comment]
This is out of my control as the export in zbrush is not something we have control over. You might want to report this to maxon.
