### ISSUE TITLE
[vcol] file transfer error (Python Traceback)

### ISSUE THREAD

**Issue by RazorLaurent** [JoseConseco/GoB#469]
Hello, I have a problem, I installed the most recent version of GOB and I get this error.

It doesn't let me transfer all the pieces to the blender and when I do it manually I get that message.

I leave the import activated and I export everything in Zbrush, it only goes to one layer

![Screenshot_3](https://github.com/JoseConseco/GoB/assets/168359808/db4fc2b7-3f96-49b7-b4e2-25fc866c72e8)

I leave the GOB as configured

![Sin título](https://github.com/JoseConseco/GoB/assets/168359808/29189666-1fb7-49e4-91d8-ae446e6a95bc)

**Comment by Marcoslubian** [comment]
I have the same error, you find any solution?

**Comment by kromar** [comment]
There is a new release which should fix your issue https://github.com/JoseConseco/GoB/releases/tag/v4_0_3

**Comment by Marcoslubian** [comment]
first of all thanks for helping me but I still have the same problem, I uninstalled zbrush and blender, I installed again, everything new without the older folder, even I installed in a new hardrive I use the new GoB you send. But the same error again:

bpy.data.window_managers["WinMan"].addon_search = "go"
bpy.context.space_data.system_folders_active = 1
Python: Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 1477, in invoke
bpy.ops.scene.gob_export(as_tool=as_tool)
File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in call
ret = _op_call(self.idname_py(), kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 1260, in execute
print(source_GoZ_Info, target_GoZ_Info)
OSError: [WinError 233] No hay ningún proceso en el otro extremo de la canalización

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 1277, in execute
print(e)
OSError: [WinError 233] No hay ningún proceso en el otro extremo de la canalización
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109


Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
