### ISSUE TITLE
GoB don't export or import yet

### ISSUE THREAD

**Issue by Marcoslubian** [JoseConseco/GoB#473]
thisis the error code I have I use the the zip you of the link your provedie but it dosn't works

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB\GoB.py", line 744, in invoke
    run_import_manually()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB\GoB.py", line 1594, in run_import_manually
    bpy.ops.scene.gob_import() #only call operator update is found (executing operatros is slow)  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB\GoB.py", line 223, in GoZit
    print("Unknown tag:{0}".format(tag))
OSError: [WinError 233] No hay ningún proceso en el otro extremo de la canalización
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109

**Comment by kromar** [comment]
Hi, thanks for reporting this issue, can you tell me what version of zbrush you are using? Are you using the maxon version?

**Comment by Marcoslubian** [comment]
Thanks for answer me, my zbrush is maxon version yes, it is zbrush 2023.2.1
________________________________

**Comment by 879096600** [comment]
I have the same problem ，zbrush2024.1

**Comment by Marcoslubian** [comment]
You could fix it?

**Comment by Marcoslubian** [comment]
Hi, there is something new about this problem I really need to fix it, please.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kromar** [comment]
Hi, no news, i have little time so it can take a while.

**Comment by Marcoslubian** [comment]
Ok, thanks for answering me and sorry for the pressure.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sangouzhi** [comment]
I have the same problem ，zbrush2024.0.2
