### ISSUE TITLE
IndexError on Export: bpy_prop_collection index out of range in GoB addon (Blender Version 4.1.1)

### ISSUE THREAD

**Issue by Limbicnation** [JoseConseco/GoB#474]
`Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-master\GoB.py", line 1477, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-master\GoB.py", line 1391, in execute
    self.exportGoZ(PATH_GOZ, context.scene, obj, f'{PATH_PROJECT}')
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-master\GoB.py", line 998, in exportGoZ
    color = active_color.data[loop.index].color_srgb
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: bpy_prop_collection[index]: index 46420 out of range, size 46420
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
`

**Comment by 879096600** [comment]
I have the same problem

**Comment by Limbicnation** [comment]
@kromar thanks for replying and for your suggestions! after reinsatalling Zbrush and restating the system aswell as the GoB Plugin , everything is working!

**Comment by kromar** [comment]
@Limbicnation im glad to hear the issue has resolved. Since i got other reports for this issue it would still be good to understand what caused it. If you have any clues what could have been the issue would be great to hear about that.
Did you also do something on the blender side? Since this happens before anything hits zbrush its surprising that reinstalling zbrush fixed this for you.

**Comment by Limbicnation** [comment]
@kromar  Yes, I can't fully recall the exact procedure, but I know that I reinstalled ZBrush and the addon. After that, it worked again. Sorry that I can't provide more information, but looking into the log files might be helpful.

**Comment by Limbicnation** [comment]
Cool, looking forward to the fix.
