### ISSUE TITLE
GoB transfer from zBrush to Blender bug

### ISSUE THREAD

**Issue by mac4kent** [JoseConseco/GoB#48]
I have zBrush 2019.1.2 and Blender 2.81 beta have some bug
From Blender GoB zBrush it work but zBrush GoB Blender nothing happen.
Need to fix update soon.
mac4kent@gmail.com Kent Davis

**Comment by OldSalty** [comment]
I have run into the same issue, I will report with console log attached.

**Comment by mac4kent** [comment]
Goooooooooooooood

**Comment by kromar** [comment]
https://github.com/JoseConseco/GoB/archive/GoZ-Blender_28.zip should be fixed in the latest version

**Comment by mac4kent** [comment]
Same 3.0.9 did not made it update 3.0.10 yet.

**Comment by kromar** [comment]
@mac4kent i did not change the version number, have you tried if it fixes the issue?

**Comment by mac4kent** [comment]
Ok I will have to inspect when I get home from hospital. I will reply you back later.

**Comment by mac4kent** [comment]
Whole video youtube.
https://youtu.be/FphftatT600


There start open zBrush then go open Blender then zBrush work on sphere then from zBrush GoB Blender because zBrush got freeze. Start video this below.
https://youtu.be/FphftatT600?t=128

**Comment by kromar** [comment]
@mac4kent i can not reproduce the freeze like you showed in the video. can you open blenders command line window and see if there are any errors when zbrush freezes?

**Comment by mac4kent** [comment]
I just open Blender 2.81 beta and I don't see Toggle System Console
![image](https://user-images.githubusercontent.com/4253305/66256253-d8a31380-e740-11e9-9754-22f03b0f933f.png)

**Comment by mac4kent** [comment]
I take test again again. When Blender 2.81 beta open.
zBrush 2019.1.2 open and create sphere and edit button and click Make PolyMesh3D button then draw to be change a little of sphere.
click GoZ button then go Blender 2.81 beta click Import button on top and wait for about 2 minutes cause appear.
THEN
zBrush draw change sphere a little then GoZ fast appear.

I just test myself. 
-----------------------------------------
First time take me 2 minutes until finally appear
second time fast appear.
-----------------------------------------

**Comment by kromar** [comment]
hm that is strange that it is that slow, i think i will need to do another profiling to see what takes so long.

**Comment by mac4kent** [comment]
sure yes that strange. Take your time not hurry hehe.

**Comment by mac4kent** [comment]
@OldSalty  would you like to take some more test if you can found out like GoZ from zBrush first place make 2 min then GoZ again appear fast. if you want to. We can do other test some more later.

**Comment by OldSalty** [comment]
I’m using the the updated version and I don’t have any serious issues yet. Just a couple problems with vertex colours I think when I’m using the new vertex colour attribute in 2.81. Other than that the new version fixed all issues for me.

**Comment by mac4kent** [comment]
Really ok @OldSalty

**Comment by schroef** [comment]
> I just open Blender 2.81 beta and I don't see Toggle System Console
> ![image](https://user-images.githubusercontent.com/4253305/66256253-d8a31380-e740-11e9-9754-22f03b0f933f.png)

Are you on OSX or linux? I dont know about Linux. But for OSX you need to open blender by using the terminal to get the console.
You can do so by right clicking on the app > Show Package Contents > Contents > MacOs >  Blender. Now open that file, first terminal will open and then a Blender instance. Now the terminal window is the console window. So all errors you see in the Terminal come from Blendr.

What i did with a couple blender versions is drag that blender file inside the app to the dock. That way it acts as a shortcut to open Blender with a console window.

You can also use this path inside terminal and press return/enter
/Applications/blender-280/Blender.app/Contents/MacOS/Blender

**Comment by mac4kent** [comment]
I have difficult understand your explain so I follow your direct.
Terminal there
Last login: Sun Nov  3 01:58:49 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Kents-iMac:~ kentdavis$ 
Kents-iMac:~ kentdavis$ 
Kents-iMac:~ kentdavis$ 
Kents-iMac:~ kentdavis$ /Applications/Blender.app/Contents/MacOS/Blender 
Read prefs: /Users/kentdavis/Library/Application Support/Blender/2.82/config/userpref.blend
found bundled python: /Applications/Blender.app/Contents/Resources/2.82/python
module changed on disk: '/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/object_print3d_utils/__init__.py' reloading...
Registered Carver
Registered Power Sequencer with 3 modules
gob updater verbose is enabled
gob Updater: Read in JSON settings from file
Info: Deleted 3 object(s)

Enabling GOZ background listener
Importing: ('/Users/Shared/Pixologic/GoZProjects/Default/PM3D_Sphere3D_1.GoZ', 'PM3D_Sphere3D_1')
tags:  b'\x89\x13\x00\x00'
tags:  b"\x11'\x00\x00"
tags:  b'!N\x00\x00'
tags:  b'\xb9\x88\x00\x00'
unknown tag:b'B\x9c\x00\x00'
try to skip it...
Info: Done
Saved session recovery to '/var/folders/lw/318hqz2x21b87m655jphz2zw0000gn/T/quit.blend'

Blender quit
Kents-iMac:~ kentdavis$

**Comment by mac4kent** [comment]
November 2, 2019 at 12:20 AM
I have Blender 2.82 Alpha (59b16e28d974)
I always say Mac only. Do not use Linux and do not use Windows.
Blender folder is no long any more. There only 1 application Blender.app without folder for now start 2.81 and up.
I have 2.82 Alpha.

TERMINAL: Last login: Sat Nov  2 07:35:19 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Kents-iMac:~ kentdavis$ /Applications/Blender.app/Contents/MacOS/Blender 
Read prefs: /Users/kentdavis/Library/Application Support/Blender/2.82/config/userpref.blend
found bundled python: /Applications/Blender.app/Contents/Resources/2.82/python
module changed on disk: '/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/object_print3d_utils/__init__.py' reloading...
Registered Carver
Registered Power Sequencer with 3 modules
gob updater verbose is enabled
gob Updater: Read in JSON settings from file
Saved session recovery to '/var/folders/lw/318hqz2x21b87m655jphz2zw0000gn/T/quit.blend'

Blender quit
Kents-iMac:~ kentdavis$

**Comment by mac4kent** [comment]
There I take screenshot.app for MacOS 10.15.1
<img width="698" alt="1 MacOS 10 15 1 About this mac" src="https://user-images.githubusercontent.com/4253305/68082733-58bea680-fddd-11e9-881e-536fb2b1e0f9.png">
 Catalina
