### ISSUE TITLE
No longer able to export face maps as polygroups?

### ISSUE THREAD

**Issue by Repsolrider88** [JoseConseco/GoB#481]
Firstly , Sorry if this a simple error on my behalf, but I use to export models from blender to zbrush using face maps as polygroups for zbrush, ive recently updated both blender and the GOB addon to newer versions but now noticed this isn't an option in the export settings in the addon in blender. Has this method been removed?

**Comment by kromar** [comment]
Yes it was removed in blender 3.6 or so and there needs to  be a new implementation done wiht face attributes.

**Comment by kromar** [comment]
Face sets are available in this branch in version 4.1.5: https://github.com/kromar/blender_GoB/tree/extensions-platform-review
