### ISSUE TITLE
Doesn't import objects ogether as Subtools

### ISSUE THREAD

**Issue by iRenwick** [JoseConseco/GoB#482]
i need to import all selected meshes at the same position as blender in one scene but it adds objects as tools and only one will be in the scene as subtool, what should i do?
more information about my problem: https://www.reddit.com/r/blenderhelp/comments/1drh8sg/gob_problem_with_exporting_to_zbrush/

**Comment by kromar** [comment]
there is a keybinding on the export button which will export as tools instead of subtools. Check out the tooltip, that should clarify it. Let me know if this persists and maybe check if there is some error in the command line of blender.

**Comment by kromar** [comment]
I released a new version, maybe its worth trying it.
https://github.com/JoseConseco/GoB/releases/tag/v4_1_0
