### ISSUE TITLE
Automatic import errors

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#487]
OK, I managed to reproduce the issue fairly quickly with a test today and the automatic import stopped working after a tracebook (screenshot below).

Steps:
1.) Enable auto import in Blender (4.2.1).
2.) Open a ZTL in ZBrush 2024 with many subtools, most of which contain subdiv levels.
3.) Send 1 selected subtool to Blender with the “GoZ” (current subtool only) button. Confirm it automatically imports into Blender.
4.) Return to ZBrush. Disable visibility of all but a group of ~ 6 subtools. Click “Visible” GoZ button (sends all visible subtools to Blender). Confirm it automatically imports into Blender. However, a message appears in my Blender console that says the following:
Info: Deleted 1 object(s)
Unknown tag:b’\x8a\x13\x00\x00’
Unknown tag:b’\x8a\x13\x00\x00’
Unknown tag:b’\x8a\x13\x00\x00’
Unknown tag:b’\x8a\x13\x00\x00’
Unknown tag:b’\x8a\x13\x00\x00’
Unknown tag:b’\x8a\x13\x00\x00’
5.) Choose a single imported subtool/object in Blender and move some vertices around in sculpt mode. Return to object mode. Send the modified object back to ZBrush with the GoB “export” button. The traceback messages in the image attached below appear. The modified object transfers successfully back to ZBrush.
6.) Attempt to send a different group of ~6 subtools from ZBrush back to Blender with the GoZ “Visible” button. *** Auto Import does NOT work in Blender***.

![Image](https://github.com/user-attachments/assets/b3748d00-9b9f-42e6-8fae-78de4f8963b0)

**Comment by kevincgmaya** [comment]
Same question.

**Comment by kromar** [comment]
I can not reproduce this error, can you still reproduce this issue with the latest version of GoB?

**Comment by kromar** [comment]
i was able to reproduce this issue and should have a fix for the next version.
