### ISSUE TITLE
GoB for ZBrush Ipad 

### ISSUE THREAD

**Issue by ilumetric** [JoseConseco/GoB#488]
Is there any possibility of adding GoB support for ipad version of ZBrush? 
As far as I understand this support can be done.

**Comment by ilumetric** [comment]
I don't think it's that simple. I couldn't find a folder like that the first time. 
In ZBrush 2025 there is a separate button for sending to iPad, and also in the settings there is tracking of incoming files. 
<img width="155" alt="image" src="https://github.com/user-attachments/assets/0da719e7-2601-44ae-bc55-c38394b119be">
![image](https://github.com/user-attachments/assets/0b08e7a6-1e3a-4380-a524-2a79c6c7e80b)

**Comment by kromar** [comment]
If the files are stored somewhere on the drive it should work. If not then that is a different story of course.
Did you try to find the files after you send them from the ipad to zbrush or vise versa?
