### ISSUE TITLE
Unable to import from zbrush

### ISSUE THREAD

**Issue by OldSalty** [JoseConseco/GoB#49]
I sent a cube to zbrush, then tried to get it bacl to blender and receive this error. I've tested mesh with and without polygroups and polypaint. All have same result.

Kind regards.

![image](https://user-images.githubusercontent.com/7090702/66009205-d2245a00-e4fc-11e9-9cec-a0a98bee416b.png)

**Comment by kromar** [comment]
https://github.com/JoseConseco/GoB/archive/GoZ-Blender_28.zip
