### ISSUE TITLE
Polygroup importing from Zbrush

### ISSUE THREAD

**Issue by Danok998** [JoseConseco/GoB#491]
Hi, I’m having a problem importing subtools into Blender. I updated the addon for Blender, and now, when I choose the same options as before, I don’t get any polygroups inside Blender. How can I solve this? The addon isn’t working on any version of Blender. I would appreciate your help.
![Screenshot 2024-09-24 145156](https://github.com/user-attachments/assets/f8d55164-f809-4d06-8638-9fc8d75ceffb)
![Screenshot 2024-09-24 145423sd](https://github.com/user-attachments/assets/4fb8ff59-c272-4531-b191-d98f527d9462)

**Comment by Danok998** [comment]
![Uploading Screenshot 2024-09-24 145423sd.png…]()

**Comment by kromar** [comment]
blender 4.0.2
GoB 4.1.0

**Comment by kromar** [comment]
Hi @Danok998, i am not able to reproduce your issue, can you give more details on what you are exporting and what you expect to see in blender? In your 2nd screenshot you show empty vertex groups but mention materials so its a bit confusing to understand what you want to show. Of course the vertex groups should also be created with your settings.

When i send the earthquake model from zbrush to blender with your settings everything seems to work fine so maybe there is something different in your models which somehow break something. Would be great to find out if that is the case.

![Image](https://github.com/user-attachments/assets/c73503e1-cf58-4a08-aca1-34e8ef9e934a)
![Image](https://github.com/user-attachments/assets/cc1dafd9-cecd-4e20-9de1-ce6a548c323d)
