### ISSUE TITLE
Error exporting from Blender 4.1

### ISSUE THREAD

**Issue by originaldjdaze** [JoseConseco/GoB#493]
Hi, i'm getting this error when trying to export back to zbrush 2024
![image](https://github.com/user-attachments/assets/3befd3aa-a6f5-451b-a56f-b06e46804b5e)

**Comment by kromar** [comment]
Hi @originaldjdaze i am not able to reproduce this error, can you provide some more details about your object that you want to send to zbrush or best provide a example blend file where this happens?
Also did you change some of the addons preferences?

**Comment by kromar** [comment]
I fixed some issues related to your report in this branch, let me know if this fixes your issues: https://github.com/kromar/blender_GoB/tree/extensions-platform-review

**Comment by originaldjdaze** [comment]
Thank you for the update!  All seems to be working well now.  
cheers
