### ISSUE TITLE
When the system drive is not the C drive, the plugin will encounter errors

### ISSUE THREAD

**Issue by pangpangdeduola** [JoseConseco/GoB#497]
Since my system is installed on the L drive instead of the C drive, I encountered an error when exporting a model from Blender to ZBrush after following the installation instructions for gob. Upon investigation, I discovered that the plugin was installed by default in 'C:\Users\Public\Pixologic'. After moving the folder to 'L:\Users\Public\Pixologic', I was able to successfully export the model to ZBrush. However, I still cannot find the gob button in the ZBrush preferences, which prevents me from exporting models from ZBrush to Blender. How can I resolve this issue?
![{1AD6CF2F-A726-4B88-908B-52614440CBF8}](https://github.com/user-attachments/assets/bc32cd4a-ae64-4bcc-a869-eebf768a1ea4)

**Comment by kromar** [comment]
Hi, i think i added the custom project path for this purpose. Let me know how it goes
![image](https://github.com/user-attachments/assets/771273c3-8cd4-4c90-b86c-d8fef3224af0)

**Comment by pangpangdeduola** [comment]
> Hi, i think i added the custom project path for this purpose. Let me know how it goesHi, i think i added the custom project path for this purpose. Let me know how it goes嗨，我想我为此目的添加了自定义项目路径。让我知道进展如何 ![image](https://private-user-images.githubusercontent.com/1472884/375470993-771273c3-8cd4-4c90-b86c-d8fef3224af0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzgzMjAsIm5iZiI6MTcyODYzODAyMCwicGF0aCI6Ii8xNDcyODg0LzM3NTQ3MDk5My03NzEyNzNjMy04Y2Q0LTRjOTAtYjg2Yy1kOGZlZjMyMjRhZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDkxMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE5N2VlYTE0ODU4ZGM5NTk4ZDFmMDA5OTUyOWViODQyY2UzNjdlOGQxOGE3NzU5MzllOWZiMDNhZTAxNzM2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WNc75vwmHFehg0gUn3lUFzd6yFjbU2ZfukZTpelF6ds)

Thank you for your reply. I changed the project address to the C drive and reinstalled goz. Then I copied the blender folder under "...\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\GoB - 4_1_2" to "C:\Users\Public\Pixologic\GoZApps". Now I can import models from zbrush to blender normally through the plugin. I hope my experience can answer questions for those who have the same problem. Thanks again.
![{E82FCC31-2925-4960-A232-031BD7900549}](https://github.com/user-attachments/assets/abf2b19d-83f6-47cb-91ee-cc33407db012)
