### ISSUE TITLE
Export issues in Blender 2.81a

### ISSUE THREAD

**Issue by 3Rton** [JoseConseco/GoB#57]
https://drive.google.com/file/d/1Lcaapi04vqjy5URhuowcaI_Fkt3BHNvJ/view?usp=drivesdk

Export seems to be broken :/

**Comment by kromar** [comment]
@3Rton i think you are using a old version of the addon, can you try to isntall this one and let me know if it solves the issue?
https://github.com/JoseConseco/GoB/archive/GoZ-Blender_28.zip

**Comment by 3Rton** [comment]
I'm an idiot. It works with this one rip.
