### ISSUE TITLE
export textures from blender to zbrush does not work (worked in 2.79?)

### ISSUE THREAD

**Issue by mac4kent** [JoseConseco/GoB#58]
I am Kent Davis.
Blender 2.82 Alpha GoB zBrush 2020 not work texture
Blender export button to go zBrush 2020 appear only object doesn't appear texture itself.
I already put Blender document File > External Data > Pack All into .blend

[Sidewalk.blend.zip](https://github.com/JoseConseco/GoB/files/3966426/Sidewalk.blend.zip)

**Comment by kromar** [comment]
confirmed that texture transfer was working in the old 2.72 version from blender to zbrush
[GoB_2-72.zip](https://github.com/JoseConseco/GoB/files/4739832/GoB_2-72.zip)

**Comment by mac4kent** [comment]
I am not use 2.7x any more. I have use Blender 2.90 Alpha and Blender 2.83

**Comment by kromar** [comment]
ah yeas i assume everybody is:D i was just trying it on the old version so i know for sure that this was possible and broke somewhere along the way^^
The plan is to make this work again for 2.83+

**Comment by mac4kent** [comment]
Oh ok. There is no long texture on properties any more. change to Materials. See youtube.
https://youtu.be/ETpc1Y-vgao
(Use Nodes) button

**Comment by kromar** [comment]
yes im aware of that. i already added support for user specific texture suffixes that i plan to use to identify/create textures in the node systems. of course there are many cases that need to be consdered so its going to be quite a bit of work to make it in a good and intuitive way for the end user.
![image](https://user-images.githubusercontent.com/1472884/83948222-22865100-a81c-11ea-8adc-c372206b1729.png)

**Comment by mac4kent** [comment]
Allright no problem

**Comment by mac4kent** [comment]
I just got download GoB for 2.8x just now. I show you picture.

![image](https://user-images.githubusercontent.com/4253305/83948660-7f114e00-a7d3-11ea-95c2-3c6aab5dd95c.png)

**Comment by kromar** [comment]
yes im still working on a big update that includes the options i show, i intend to fix the texture transfer in that as well. here is the latest version if you want to try the current state: https://github.com/kromar/blender_GoB/tree/b3_3_7

**Comment by mac4kent** [comment]
Sureeeeeeee and I get download from your link.

**Comment by mac4kent** [comment]
![image](https://user-images.githubusercontent.com/4253305/83949735-47f26b00-a7da-11ea-97d1-5019e2b8cfe8.png)

**Comment by mac4kent** [comment]
Some one made
https://www.patreon.com/posts/3d-model-bugs-14969357

I fix Blender 2.90 Alpha this my "Bugs Bunny.zip and open "BugsBunny.blend"
https://www.dropbox.com/s/jlxdxzyl2srbgf0/Bugs%20Bunny.zip?dl=0
![image](https://user-images.githubusercontent.com/4253305/83950230-ffd54780-a7dd-11ea-8bb3-4bbb47565ebd.png)
![image](https://user-images.githubusercontent.com/4253305/83950233-1085bd80-a7de-11ea-87b5-71ab9d45797d.png)
