### ISSUE TITLE
Decimated geo from Zbrush imports incorrectly 

### ISSUE THREAD

**Issue by CoUnTDaBBuLa** [JoseConseco/GoB#61]
When I use the add-on to bring my decimated Hp to blender for retopo, the data must be being read incorrectly. The models are covered in shading issues from verts overlapping edges, they seem like they should be connected to the edge but they aren't which creates shading problems. I confirmed that this was a problem within the add-on by testing the same subtool exported via OBJ to Blender and no smoothing issues are present.

**Comment by CoUnTDaBBuLa** [comment]
![Overlapping](https://user-images.githubusercontent.com/39884025/77808723-fb184880-7062-11ea-94a6-f116cbbcdeca.jpg)

**Comment by kromar** [comment]
hm that looks strange, can you show the same region in zbrush with polyframe enabled?

**Comment by CoUnTDaBBuLa** [comment]
I apologize, the issue is present in the zbrush polyframe and the only reason it worked as an OBJ was because I forgot to tick smooth shading, therefore it must be an issue somewhere in decimation master.

**Comment by kromar** [comment]
@CoUnTDaBBuLa this is a common issue with decimation, maybe you want to try zremesher instead

**Comment by CoUnTDaBBuLa** [comment]
@kromar I was just trying to get the high-poly so I could retopo & bake it down, I wasn't trying to get a low-poly from it or anything. It's a small toolbox without a lot of smaller details and shouldn't need the 1 mil. polys to get no shading issues. I've baked a lot of props but I've never run into these issues using Decimation Master. Thanks for your help, I appreciate it.
