### ISSUE TITLE
Import section missing

### ISSUE THREAD

**Issue by niazahmedkhan** [JoseConseco/GoB#75]
Hey, when I install this in my blender 2.82 version it says import section error. I cant import from ZBrush. 
![Screenshot_8](https://user-images.githubusercontent.com/63477046/81354305-14de8e00-90ed-11ea-8d10-2ab911e4803b.jpg)

[bug](https://user-images.githubusercontent.com/63477046/81354353-2d4ea880-90ed-11ea-8612-b2dfa29b1474.jpg)

see this .and let me know okay

**Comment by zelfor** [comment]
![image](https://user-images.githubusercontent.com/8266812/81397044-f1234400-90fc-11ea-83be-ba7774698349.png)
![image](https://user-images.githubusercontent.com/8266812/81397010-dea90a80-90fc-11ea-81f7-8663314270d8.png)

I updated the Add-On and this message has appeared since then ...

**Comment by niazahmedkhan** [comment]
Why this is not fixing yet??

**Comment by kromar** [comment]
@niazahmedkhan thanks for reporting this issue. i was already working on the next versions i did not expect any issues with 2.82. i will see if i can get a fix out for this tomorrow.

**Comment by kromar** [comment]
@niazahmedkhan  Please try the latest release, it should fix the issue you have.

https://github.com/JoseConseco/GoB/releases/tag/v3_2_4

**Comment by niazahmedkhan** [comment]
Hello,
I have checked it and the issue fixed. Thanks fixing the issue. It works
fine now. I hope in the future you will make some good addon for the
community Witing for those. You have done a great job. Wish you all the
best.
