### ISSUE TITLE
I can't install addon on blender 2.8 (getting 'NameError')

### ISSUE THREAD

**Issue by XnetLoL** [JoseConseco/GoB#8]
When I try to install GoB_2_8.py I get the following issue:
https://i.gyazo.com/c2595903961a2dc0a570c92a8d5235b0.png

That's my userpref.py file:
https://quickfileshare.org/2AMk/userpref.py

I had no problems installing it on zBrush.

**Comment by JoseConseco** [comment]
Sorry but this error report dosen't help. Is there more info in blender console?
Something related to file: GoB_2_8.py ?

**Comment by XnetLoL** [comment]
Hi, I downloaded Blender again and now it's working. I guess it was due a decompression error or something.
