### ISSUE TITLE
Blender's Face Maps are not reflected on Zbrush's Poly Groups.

### ISSUE THREAD

**Issue by Tsukasa-YAMATO** [JoseConseco/GoB#87]
Note: Facemaps are exported via vertex groups which is a leftover from the vertex group export only, rewrite export to use face maps directly.

Hello. I'm new to GitHub. Can I write bug reports here?
Windows 10 Pro, Blender 2.82a, GoB 3.2.5

The "From Face Maps" function of Poly Groups  in the Preferences of Blender does not work.
The vertex groups are forcibly reflected in the Poly Groups on Zbrush, I guess. Is this a bug? Please see the attached image.

![2020-05-19_23h57_45](https://user-images.githubusercontent.com/65609416/82342480-a5da3100-9a2c-11ea-9d9d-ceff85ed9cf1.jpg)

![2020-05-19_23h44_04](https://user-images.githubusercontent.com/65609416/82341799-da99b880-9a2b-11ea-99e2-f2613da17e6d.jpg)

![2020-05-19_23h38_15](https://user-images.githubusercontent.com/65609416/82341789-d53c6e00-9a2b-11ea-9709-ee220660c3f2.jpg)

**Comment by kromar** [comment]
@Tsukasa-YAMATO yes please report issues if you fiond some and thanks for this report, it definitely looks like a bug.

**Comment by Tsukasa-YAMATO** [comment]
Thank you for your reply.
This bug is very troublesome because Blender overwrites polygroup areas when doing low poly modeling in Zbrush. And this bug is critical because there are many cases which one face is sandwiched between the same polygroups.

![2020-05-20_03h29_08](https://user-images.githubusercontent.com/65609416/82365068-1abc6380-9a4b-11ea-882d-cafa6a99ded1.jpg)

I hope it will be corrected.

**Comment by kromar** [comment]
yes i completely understand the issue. I was thinking about this issue and currently the data is sent via vertices so i am not sure how its possible to avoid this. I will have to investigate closer to see what can be done about it.

**Comment by Tsukasa-YAMATO** [comment]
I don't know the structure in detail, but Blender's facemaps can correctly represent Zbrush's polygroups, so it would be ideal if the facemaps could be converted back to polygroups. (Since it can already get the facemaps from Zbrush's mesh, I feel like it can return the facemaps as Zbrush's polygroups, is it difficult?)

**Comment by kromar** [comment]
The thing is that at the moment facemaps from blender are converted to vertex groups (and the import is also done via vertex groups) and if you try to make a vertex group like you showed in your examples it will fill the gaps in between so i need to check that code if its possible to send faces directly without the conversion. This makes me wonder if we can also get some unexpected behaviour on import in different scenarios.

I also found another bug with facemaps, theres some issue going on if there is a empty facemap and some other strange override of the maps so only the last in the stack is represented in zbrush.

**Comment by Tsukasa-YAMATO** [comment]
Now I understood that it's not a small coding mistake or something. This is a difficult problem about polygroup keeping.
I may think about this and try to search some hints as I possible.
Thank you for your time.

**Comment by kromar** [comment]
I was checking out the code and as far as i can tell it should be possible to do it directly from the face maps, so its just a leftover of the old implementation that i did not adapt to this (somehow missed it). 
But yes it will be a bit of work and not a quick fix, im currently working on some other refactoring on the import side and planned to do some improvements on the export so i will most likely tackle this issue at that stage.
you will probably see some updates in this ticket when i start working on it but i make sure to give you a vertision to test once its done.

**Comment by Tsukasa-YAMATO** [comment]
Thank you for your reactions!
I have registered this site with Watching, and email notifications come each time of some response.
I sincerely hope this issue can be solved smartly.

**Comment by kromar** [comment]
@Tsukasa-YAMATO i made a bit progress, the basic export seems to work directly from face maps, so no detour via the vertex groups YAY! 
It works on a very basic example, however produces some funky results on more complex models at the moment. There is most likely some issue remaining with the order in which the faces are writtin to the file. Im confident i can fix this soon-ish.

![Screen Shot 05-24-20 at 11 57 AM](https://user-images.githubusercontent.com/1472884/82751346-cb619480-9db6-11ea-9614-3a93c868b0d0.PNG)

![Screen Shot 05-24-20 at 12 01 PM](https://user-images.githubusercontent.com/1472884/82751352-d4eafc80-9db6-11ea-99b8-1a39bcf89079.PNG)

**Comment by Tsukasa-YAMATO** [comment]
Thank you for trying to fix the bug.
I am glad to hear that the basic solution could be found.
It's definitely a funky Rubik's Cube.

If the Face Maps correspond to polygroups correctly when it is sent from Zbrush to Blender, I think it would be logically reversible. You will be able to  realize sending Face Maps as polygroups in Zbrush.

I'm looking forward to implement.

**Comment by kromar** [comment]
yes that is exactly what im going to look at now to see how zbrush sends thee data and then reconstruct the same pattern.

**Comment by kromar** [comment]
i got it working but its **very slow** at the moment, if you give it a try and see if you get any strange behavior would be great. 

https://github.com/kromar/blender_GoB/archive/b3_3_4.zip

**Comment by Tsukasa-YAMATO** [comment]
Thank you for your quick work.
I will try to answer after a thorough test. Both you and I need good sleep and rest for getting a good work.

Please wait without in rush.
I will answer it within about 24 hours, if I don't have any troubles.

**Comment by Tsukasa-YAMATO** [comment]
I have tried GoB Ver.3.3.4.
I have confirmed an issue where the number of vertex groups and Face Maps entries doubles. The problem is that new entries are added while leaving empty entries with no vertex data. However, the issue of "preserving polygroups" seems to have been resolved.

I deleted the empty entries (from both vertex groups and Face Maps) and sent meshes from Blender to Zbrush,  and it worked well.

So, immediately after importing mesh data from Zbrush to Blender with GoB, it would like to have a loop process that scans all Face Maps entries and deletes empty Face Maps entries that do not contain vertices. Do the same to remove empty entries in the vertex group.

Of course, any empty entries which users have created before will also be deleted, but it is unlikely that users will create such empty entries before using GoB.
Rather, it is preferable if the empty entries are cleanly deleted. So even if users transfer meshes between Zbrush and Blender in GoB many times, it avoids increase of unnecessary empty entries.


A tentative action that the user can take is to delete objects in Blender and transfer meshes from Zbrush to Blender again when users feel like it. This will remove the empty entries from Blender. :)

(But implementation for clean up the empty entries is the most smart aproach, I guess.)

**Comment by Tsukasa-YAMATO** [comment]
I have found some bugs.
OFF the debug mode is a bit unstable. I will use this with ON for a while.

![2020-05-25_17h09_58](https://user-images.githubusercontent.com/65609416/82796820-1eb80d80-9eb1-11ea-91b3-1cf6fa7aaf9e.jpg)


Vertex groups and Face Maps were not generated when the mesh have many edges connected to on one vertex.

![2020-05-25_16h57_59](https://user-images.githubusercontent.com/65609416/82797060-7eaeb400-9eb1-11ea-9dfc-d8f1e454ba95.jpg)

When I deleted the concentrated vertex, it worked well.

![2020-05-25_16h55_24](https://user-images.githubusercontent.com/65609416/82797207-bb7aab00-9eb1-11ea-9040-f13d4783898c.jpg)
 
Although the topology in which edges are concentrated at one vertex is not beautiful, it is difficult to avoid because it is often used in modeling. Probably an algorithmic bug. My guess is that there is a bug in creating the "vertex groups". (Maybe creating Face Maps shouldn't be a problem.)
Please check it out.

**Comment by kromar** [comment]
thanks a lot for the review! hm that is strange with the cylinder cap! i think with the examples you provided and the error messages from the console i should be able to reproduce and fix those issue.

very strange that you get an error when disabling debug, that should only take some timing of various operations.

About the duplication of the maps, since in the end its supposed to be face sets and not face maps which are used in blenders sculpt mode im not sure how that will look like when the development of that feature is more mature. currently im just using the face maps since they will produce unique face selection and can be loaded into face sets. however when paining face sets in sculpt mode they are not synced with face maps and i have not found a way to currently access that data so i assume its not exposed "yet" to python.
maybe in the future the user does not even see the maps and the cleanup question might not be relevant since they are not presented to the user.
I think i agree with you the currently only the relevant maps should be kept and the others deleted.
i also had another idea that i want to follow up with, that would be to write a function to produce the color code for zbrush and then convert the ones the user created to those and read them also on import so no duplication should happen in the first place:O

**Comment by kromar** [comment]
i think the first error with the debug is not related to the debug, since i create a random "color code" it looks more that you got unlucky and got a color code that is not compatible with the formatting. i kinda expected this to cause some issues after i understood that its actual color code^^

**Comment by kromar** [comment]
hm the issue with the cylinder is strange, it seems to be some issue when the mesh contains triangles. That seems to break most of the import for some reason
